import { IMapRaw } from "../../components/Maps";

/* tslint:disable max-line-length */

export const Route2: IMapRaw = {
    "name": "Route 2",
    "theme": "Viridian City from Pallet Town",
    "locationDefault": "Viridian Forest Top",
    "locations": {
        "Viridian Forest Top": {
            "area": "Land",
            "direction": 0
        },
        "Viridian Forest Bottom": {
            "area": "Land",
            "push": true
        }
    },
    "areas": {
        "Land": {
            "allowCycling": true,
            "width": 896,
            "height": 2368,
            "creation": [
                { "thing": "ThemePlayer", "x": 384, "width": 64, "height": 1600, "theme": "Viridian City from Pallet Town" },
                { "thing": "AreaSpawner", "width": 896, "map": "Pewter City", "area": "Land", "direction": 1, "offsetX": -192 },
                { "thing": "DirtMedium", "width": 384, "height": 64 },
                { "thing": "PlantSmall", "width": 384, "height": 64 },
                { "thing": "DirtMedium", "x": 448, "width": 480, "height": 64 },
                { "thing": "PlantSmall", "x": 448, "width": 480, "height": 64 },
                { "macro": "Checkered", "things": ["DirtClean", "DirtWhite"], "x": 384, "xnum": 2 /* fixed */, "ynum": 40 },
                { "thing": "DirtMedium", "y": 64, "width": 128, "height": 2304 },
                { "thing": "PlantSmall", "y": 64, "width": 128, "height": 2304 },
                { "thing": "DirtMedium", "x": 768, "y": 64, "width": 160, "height": 2304 },
                { "thing": "PlantSmall", "x": 768, "y": 64, "width": 160, "height": 2304 },
                { "thing": "DirtMedium", "x": 128, "y": 64, "width": 256, "height": 256 },
                { "thing": "PlantSmall", "x": 128, "y": 64, "width": 256, "height": 64 },
                { "thing": "DirtMedium", "x": 448, "y": 64, "width": 320, "height": 64 },
                { "thing": "PlantSmall", "x": 448, "y": 64, "width": 320, "height": 64 },
                { "thing": "Grass", "x": 128, "y": 128, "width": 256, "height": 192 },
                { "thing": "DirtWhite", "x": 448, "y": 128, "width": 64, "height": 128 },
                { "thing": "FenceVertical", "x": 448, "y": 128, "width": 32, "height": 128 },
                { "thing": "DirtLight", "x": 512, "y": 128, "width": 256, "height": 128 },
                { "thing": "DirtWhite", "x": 448, "y": 256 },
                { "macro": "Mountain", "x": 448, "y": 256, "width": 256, "height": 128, "top": true, "right": true, "bottom": true, "left": true, "opening": true },
                { "thing": "DirtLight", "x": 672, "y": 256, "width": 96, "height": 128 },
                { "thing": "DirtLight", "x": 128, "y": 320, "width": 320, "height": 64 },
                { "thing": "DirtMedium", "x": 128, "y": 384, "width": 320, "height": 192 },
                { "thing": "PlantSmall", "x": 128, "y": 384, "width": 96 },
                { "thing": "PlantSmall", "x": 256, "y": 384, "height": 64 },
                { "thing": "Tree", "x": 288, "y": 384 },
                { "thing": "PlantSmall", "x": 320, "y": 384, "width": 128 },
                { "thing": "DirtLight", "x": 448, "y": 384, "width": 128, "height": 128 },
                { "thing": "DirtMedium", "x": 576, "y": 384, "width": 192, "height": 64 },
                { "macro": "Checkered", "things": ["", "Flower"], "x": 576, "y": 400, "xnum": 8 /* fixed */, "ynum": 2 /* fixed */, "xwidth": 16, "yheight": 16 },
                { "thing": "PlantSmall", "x": 192, "y": 416 },
                { "thing": "Sign", "x": 480, "y": 416 },
                { "thing": "HiddenTransporter", "x": 224, "y": 416, "directionRequired": 8, "entrance": "Viridian Forest Top", "transport": { "map": "Viridian Forest", "location": "Gate North Door North" } },
                { "macro": "Building", "x": 192, "y": 448, "door": true },
                { "thing": "DirtLight", "x": 576, "y": 448, "width": 192, "height": 64 },
                { "thing": "DirtMedium", "x": 448, "y": 512, "width": 256, "height": 64 },
                { "thing": "DirtLight", "x": 704, "y": 512, "width": 64, "height": 256 },
                { "thing": "FenceWide", "x": 128, "y": 544, "width": 64 },
                { "thing": "FenceWide", "x": 320, "y": 544, "width": 256 },
                { "thing": "BrickRoad", "x": 128, "y": 576, "width": 256, "height": 64 },
                { "thing": "DirtMedium", "x": 384, "y": 576, "width": 192, "height": 192 },
                { "thing": "PlantSmall", "x": 384, "y": 576, "width": 192, "height": 192 },
                { "thing": "DirtMedium", "x": 576, "y": 576, "width": 128, "height": 64 },
                { "thing": "DirtLight", "x": 128, "y": 640, "width": 256, "height": 64 },
                { "thing": "DirtLight", "x": 576, "y": 640, "width": 128, "height": 128 },
                { "macro": "House", "x": 576, "y": 640, "door": true },
                { "thing": "Ledge", "x": 128, "y": 688, "width": 256, "jagged": true },
                { "thing": "DirtMedium", "x": 128, "y": 704, "width": 64, "height": 64 },
                { "thing": "Grass", "x": 128, "y": 704, "width": 64, "height": 64 },
                { "macro": "Checkered", "things": ["DirtClean", "DirtWhite"], "x": 192, "y": 704, "xnum": 2 /* fixed */, "ynum": 2 /* fixed */ },
                { "thing": "DirtMedium", "x": 256, "y": 704, "width": 128, "height": 64 },
                { "thing": "Grass", "x": 256, "y": 704, "width": 128, "height": 64 },
                { "thing": "DirtMedium", "x": 128, "y": 768, "width": 640, "height": 704 },
                { "thing": "PlantSmall", "x": 128, "y": 768, "width": 448, "height": 512 },
                { "thing": "PlantSmall", "x": 576, "y": 768, "height": 64 },
                { "thing": "Tree", "x": 608, "y": 768 },
                { "thing": "PlantSmall", "x": 640, "y": 768, "width": 128 },
                { "thing": "Ledge", "x": 576, "y": 944, "width": 96, "crumbleRight": true },
                { "thing": "LedgeOpening", "x": 672, "y": 944 },
                { "thing": "Ledge", "x": 704, "y": 944, "width": 64 },
                { "macro": "Checkered", "things": ["", "Flower"], "x": 704, "y": 976, "xnum": 4 /* fixed */, "ynum": 2 /* fixed */, "xwidth": 16, "yheight": 16 },
                { "thing": "Ledge", "x": 576, "y": 1072, "width": 96, "crumbleRight": true },
                { "thing": "LedgeOpening", "x": 672, "y": 1072 },
                { "thing": "Ledge", "x": 704, "y": 1072, "width": 64 },
                { "macro": "Checkered", "things": ["", "Flower"], "x": 704, "y": 1104, "xnum": 4 /* fixed */, "ynum": 2 /* fixed */, "xwidth": 16, "yheight": 16 },
                { "thing": "FenceWide", "x": 576, "y": 1184, "width": 64 },
                { "thing": "FenceWide", "x": 704, "y": 1184, "width": 64 },
                { "macro": "Building", "x": 576, "y": 1216, "width": 192, "door": true },
                { "thing": "PlantSmall", "x": 128, "y": 1280, "width": 96 },
                { "thing": "PlantSmall", "x": 256, "y": 1280 },
                { "thing": "Tree", "x": 288, "y": 1280 },
                { "thing": "PlantSmall", "x": 320, "y": 1280, "width": 256 },
                { "thing": "PlantSmall", "x": 192, "y": 1312 },
                { "thing": "PlantSmall", "x": 256, "y": 1312 },
                { "thing": "PlantSmall", "x": 448, "y": 1312, "width": 128, "height": 160 },
                { "macro": "Building", "x": 192, "y": 1344, "width": 128, "height": 128, "door": true, "entrance": "Viridian Forest Bottom", "transport": { "map": "Viridian Forest", "location": "Gate South Door South" } },
                { "thing": "FenceWide", "x": 128, "y": 1440, "width": 64 },
                { "thing": "FenceWide", "x": 320, "y": 1440, "width": 128 },
                { "thing": "Ledge", "x": 576, "y": 1456, "crumbleRight": true },
                { "thing": "LedgeOpening", "x": 608, "y": 1456 },
                { "thing": "Ledge", "x": 640, "y": 1456, "width": 128 },
                { "thing": "BrickRoad", "x": 128, "y": 1472, "width": 320, "height": 64 },
                { "thing": "DirtMedium", "x": 448, "y": 1472, "width": 320, "height": 800 },
                { "thing": "PlantSmall", "x": 480, "y": 1472, "height": 256 },
                { "thing": "Pokeball", "x": 544, "y": 1504 },
                { "thing": "DirtLight", "x": 128, "y": 1536, "width": 256, "height": 64 },
                { "macro": "Checkered", "things": ["DirtClean", "DirtWhite"], "x": 384, "y": 1536, "xnum": 2 /* fixed */, "ynum": 2 /* fixed */ },
                { "macro": "Checkered", "things": ["", "Flower"], "x": 640, "y": 1552, "xnum": 8 /* fixed */, "ynum": 2 /* fixed */, "xwidth": 16, "yheight": 16 },
                { "thing": "Ledge", "x": 128, "y": 1584, "width": 256, "jagged": true },
                { "thing": "DirtMedium", "x": 128, "y": 1600, "width": 64, "height": 768 },
                { "macro": "Checkered", "things": ["DirtClean", "DirtWhite"], "x": 192, "y": 1600, "xnum": 2 /* fixed */, "ynum": 48 },
                { "thing": "DirtMedium", "x": 256, "y": 1600, "width": 192, "height": 320 },
                { "thing": "Grass", "x": 256, "y": 1600, "width": 192, "height": 128 },
                { "macro": "Checkered", "things": ["", "Flower"], "x": 128, "y": 1616, "xnum": 4 /* fixed */, "ynum": 2 /* fixed */, "xwidth": 16, "yheight": 16 },
                { "thing": "Ledge", "x": 512, "y": 1648, "width": 96, "crumbleRight": true },
                { "thing": "LedgeOpening", "x": 608, "y": 1648 },
                { "thing": "Ledge", "x": 640, "y": 1648, "width": 128 },
                { "macro": "Checkered", "things": ["", "Flower"], "x": 128, "y": 1680, "xnum": 4 /* fixed */, "ynum": 2 /* fixed */, "xwidth": 16, "yheight": 16 },
                { "thing": "Tree", "x": 512, "y": 1728 },
                { "macro": "Checkered", "things": ["", "Flower"], "x": 128, "y": 1744, "xnum": 4 /* fixed */, "ynum": 2 /* fixed */, "xwidth": 16, "yheight": 16 },
                { "thing": "PlantSmall", "x": 320, "y": 1760, "width": 256 },
                { "thing": "PlantSmall", "x": 288, "y": 1792, "width": 256, "height": 64 },
                { "macro": "Checkered", "things": ["", "Flower"], "x": 128, "y": 1808, "xnum": 4 /* fixed */, "ynum": 2 /* fixed */, "xwidth": 16, "yheight": 16 },
                { "thing": "Pokeball", "x": 544, "y": 1792 },
                { "thing": "PlantSmall", "x": 320, "y": 1856, "width": 224 },
                { "macro": "Checkered", "things": ["", "Flower"], "x": 128, "y": 1872, "xnum": 4 /* fixed */, "ynum": 2 /* fixed */, "xwidth": 16, "yheight": 16 },
                { "macro": "Checkered", "things": ["", "Flower"], "x": 576, "y": 1872, "xnum": 4 /* fixed */, "ynum": 2 /* fixed */, "xwidth": 16, "yheight": 16 },
                { "thing": "PlantSmall", "x": 512, "y": 1888, "height": 96 },
                { "thing": "DirtLight", "x": 256, "y": 1920, "width": 192, "height": 64 },
                { "macro": "Checkered", "things": ["", "Flower"], "x": 128, "y": 1936, "xnum": 4 /* fixed */, "ynum": 2 /* fixed */, "xwidth": 16, "yheight": 16 },
                { "macro": "Checkered", "things": ["", "Flower"], "x": 576, "y": 1936, "xnum": 8 /* fixed */, "ynum": 2 /* fixed */, "xwidth": 16, "yheight": 16 },
                { "thing": "PlantSmall", "x": 128, "y": 1984, "width": 64, "height": 384 },
                { "thing": "DirtMedium", "x": 192, "y": 1984, "width": 192, "height": 128 },
                { "thing": "DirtLight", "x": 384, "y": 1984, "width": 64, "height": 256 },
                { "thing": "Tree", "x": 512, "y": 1984 },
                { "thing": "PlantSmall", "x": 512, "y": 2016, "width": 64 },
                { "thing": "Ledge", "x": 192, "y": 2032, "width": 160, "crumbleRight": true },
                { "thing": "LedgeOpening", "x": 352, "y": 2032 },
                { "thing": "Ledge", "x": 384, "y": 2032, "width": 128, "crumbleLeft": true },
                { "thing": "Ledge", "x": 576, "y": 2032, "crumbleRight": true },
                { "thing": "LedgeOpening", "x": 608, "y": 2032 },
                { "thing": "Ledge", "x": 640, "y": 2032, "width": 128 },
                { "thing": "PlantSmall", "x": 512, "y": 2048, "height": 192 },
                { "macro": "Checkered", "things": ["", "Flower"], "x": 192, "y": 2064, "xnum": 8 /* fixed */, "ynum": 2 /* fixed */, "xwidth": 16, "yheight": 16 },
                { "thing": "DirtLight", "x": 192, "y": 2112, "width": 192, "height": 64 },
                { "macro": "Checkered", "things": ["", "Flower"], "x": 576, "y": 2128, "xnum": 8 /* fixed */, "ynum": 2 /* fixed */, "xwidth": 16, "yheight": 16 },
                { "thing": "Sign", "x": 288, "y": 2144 },
                { "macro": "Checkered", "things": ["DirtClean", "DirtWhite"], "x": 192, "y": 2176, "xnum": 2 /* fixed */, "ynum": 4 /* fixed */ },
                { "thing": "DirtMedium", "x": 256, "y": 2176, "width": 128, "height": 64 },
                { "macro": "Checkered", "things": ["", "Flower"], "x": 256, "y": 2192, "xnum": 8 /* fixed */, "ynum": 2 /* fixed */, "xwidth": 16, "yheight": 16 },
                { "macro": "Checkered", "things": ["", "Flower"], "x": 576, "y": 2192, "xnum": 8 /* fixed */, "ynum": 2 /* fixed */, "xwidth": 16, "yheight": 16 },
                { "macro": "Checkered", "things": ["DirtClean", "DirtWhite"], "x": 256, "y": 2240, "xnum": 6 /* fixed */, "ynum": 2 /* fixed */ },
                { "thing": "Tree", "x": 512, "y": 2240 },
                { "thing": "DirtMedium", "x": 448, "y": 2272, "width": 320, "height": 96 },
                { "thing": "PlantSmall", "x": 448, "y": 2272, "width": 320, "height": 96 },
                { "thing": "DirtMedium", "x": 192, "y": 2304, "width": 128, "height": 64 },
                { "thing": "PlantSmall", "x": 192, "y": 2304, "width": 128, "height": 64 },
                { "thing": "DirtWhite", "x": 320, "y": 2304, "width": 64, "height": 64 },
                { "thing": "FenceVertical", "x": 320, "y": 2304, "width": 32, "height": 64 },
                { "thing": "ThemePlayer", "x": 352, "y": 2304, "width": 96, "theme": "Viridian City from Pallet Town" },
                { "macro": "Checkered", "things": ["DirtClean", "DirtWhite"], "x": 384, "y": 2304, "xnum": 2 /* fixed */, "ynum": 2 /* fixed */ },
                { "thing": "AreaSpawner", "y": 2336, "width": 2432, "map": "Viridian City", "area": "Land", "direction": 1, "offsetX": -192 }
            ]
        }
    }
};

/* tslint:enable max-line-length */
