/* This file was auto-generated by gulp-shenanigans */

import { MochaLoader } from "./utils/MochaLoader";

declare var require: any;
declare var testPaths: any;

export const mochaLoader: MochaLoader = new MochaLoader(mocha);

/**
 * Recursively loads test paths under mocha loader.
 * 
 * @param loadingPaths   Test paths to load.
 * @param i   Which index test path to load.
 * @param onComplete   A callback for when loading is done.
 */
function loadTestPaths(loadingPaths: string[], i: number, onComplete: () => void): void {
    "use strict";

    if (i >= loadingPaths.length) {
        onComplete();
        return;
    }

    mochaLoader.setTestPath(loadingPaths[i]);
    require(
        [loadingPaths[i]],
        (): void => {
            loadTestPaths(loadingPaths, i + 1, onComplete);
        });
}

loadTestPaths(
    testPaths,
    0,
    (): void => {
        mochaLoader.describeTests();
        mochaLoader.run();
    });
