import { MapRaw } from "../../sections/Maps";

export const PalletTown: MapRaw = {
    name: "Pallet Town",
    theme: "Pallet Town",
    locationDefault: "Player's House Door",
    locations: {
        "Player's House Door": {
            area: "Land",
            direction: 2,
            push: true,
        },
        "Player's House Floor 1 Door": {
            area: "Player's House",
            direction: 0,
        },
        "Player's House Floor 1 Stairs": {
            area: "Player's House",
            direction: 3,
        },
        "Player's House Floor 2 Stairs": {
            area: "Player's House Floor 2",
            direction: 3,
        },
        "Start Game": {
            area: "Player's House Floor 2",
            xloc: 96,
            yloc: 160,
            direction: 0,
        },
        "Rival's House Door": {
            area: "Land",
            direction: 2,
            push: true,
        },
        "Rival's House Floor 1 Door": {
            area: "Rival's House",
            direction: 0,
        },
        "Oak's Lab Door": {
            area: "Land",
            direction: 2,
            push: true,
        },
        "Oak's Lab Floor 1 Door": {
            area: "Oak's Lab",
            direction: 0,
        },
    },
    areas: {
        Land: {
            allowCycling: true,
            width: 608,
            height: 544,
            wildPokemon: {
                grass: [
                    {
                        title: "PIDGEY".split(""),
                        levels: [2, 3, 4, 5],
                        rate: 0.55,
                    },
                    {
                        title: "RATTATA".split(""),
                        levels: [2, 3, 4],
                        rate: 0.45,
                    },
                ],
                fishing: {
                    old: [
                        {
                            title: "MAGIKARP".split(""),
                            levels: [5],
                            rate: 1,
                        },
                    ],
                    good: [
                        {
                            title: "POLIWAG".split(""),
                            levels: [10],
                            rate: 0.5,
                        },
                        {
                            title: "GOLDEEN".split(""),
                            levels: [10],
                            rate: 0.5,
                        },
                    ],
                    super: [
                        {
                            title: "POLIWAG".split(""),
                            levels: [15],
                            rate: 0.5,
                        },
                        {
                            title: "TENTACOOL".split(""),
                            levels: [15],
                            rate: 0.5,
                        },
                    ],
                },
            },
            creation: [
                {
                    actor: "AreaSpawner",
                    width: 608,
                    height: 544,
                    map: "Route 1",
                    area: "Land",
                    direction: 0,
                },
                { actor: "FenceWide", width: 320 },
                { actor: "Grass", x: 320, width: 64 },
                {
                    actor: "CutsceneTriggerer",
                    x: 320,
                    width: 64,
                    cutscene: "OakIntro",
                    singleUse: true,
                    requireOverlap: true,
                    id: "OakIntroGrassTriggerer",
                },
                { actor: "FenceWide", x: 384, width: 256 },
                { actor: "FenceWide", y: 32, height: 512 },
                { actor: "DirtMedium", width: 640 },
                { actor: "DirtMedium", y: 32, width: 64, height: 512 },
                {
                    macro: "Checkered",
                    actors: ["DirtClean", "DirtWhite"],
                    x: 64,
                    y: 32,
                    xnum: 16,
                    ynum: 2,
                    offset: 4,
                },
                { actor: "DirtMedium", x: 576, y: 32, height: 512, width: 64 },
                { actor: "FenceWide", x: 608, y: 32, height: 512 },
                {
                    macro: "House",
                    x: 128,
                    y: 64,
                    stories: 2,
                    door: true,
                    entrance: "Player's House Door",
                    transport: { map: "Pallet Town", location: "Player's House Floor 1 Door" },
                },
                {
                    macro: "House",
                    x: 384,
                    y: 64,
                    stories: 2,
                    door: true,
                    entrance: "Rival's House Door",
                    transport: { map: "Pallet Town", location: "Rival's House Floor 1 Door" },
                },
                { actor: "DirtLight", x: 64, y: 96, width: 64, height: 64 },
                { actor: "DirtLight", x: 320, y: 96, width: 64, height: 64 },
                {
                    macro: "Checkered",
                    actors: ["DirtClean", "DirtWhite"],
                    x: 128,
                    y: 96,
                    xnum: 6,
                    ynum: 2,
                },
                {
                    macro: "Checkered",
                    actors: ["DirtClean", "DirtWhite"],
                    x: 384,
                    y: 96,
                    xnum: 6,
                    ynum: 2,
                },
                { actor: "Sign", x: 96, y: 128, dialog: "%%%%%%%PLAYER%%%%%%%'s house" },
                { actor: "Sign", x: 352, y: 128, dialog: "%%%%%%%RIVAL%%%%%%%'s house" },
                {
                    macro: "Checkered",
                    actors: ["DirtClean", "DirtWhite"],
                    x: 64,
                    y: 160,
                    xnum: 16,
                    ynum: 2,
                },
                {
                    macro: "Checkered",
                    actors: ["DirtClean", "DirtWhite"],
                    x: 64,
                    y: 224,
                    xnum: 2,
                    ynum: 6,
                },
                {
                    actor: "Lady",
                    x: 96,
                    y: 224,
                    roaming: true,
                    dialog: [
                        "I'm raising %%%%%%%POKEMON%%%%%%% too!",
                        "When they get strong, they can protect me!",
                    ],
                },
                { actor: "DirtLight", x: 128, y: 224, width: 128, height: 64 },
                {
                    macro: "Checkered",
                    actors: ["DirtClean", "DirtWhite"],
                    x: 256,
                    y: 224,
                    xnum: 2,
                    ynum: 6,
                },
                {
                    macro: "HouseLarge",
                    x: 320,
                    y: 224,
                    width: 192,
                    height: 128,
                    door: true,
                    stories: 2,
                    white: { start: 336, end: 384 },
                    id: "Oak's Lab Door",
                    entrance: "Oak's Lab Door",
                    transport: { map: "Pallet Town", location: "Oak's Lab Floor 1 Door" },
                },
                {
                    macro: "Checkered",
                    actors: ["DirtClean", "DirtWhite"],
                    x: 320,
                    y: 224,
                    xnum: 8,
                    ynum: 4,
                },
                { actor: "FenceVertical", x: 128, y: 256, width: 96 },
                {
                    actor: "Sign",
                    x: 224,
                    y: 256,
                    dialog: "PALLET TOWN \n Shades of your journey await!",
                },
                { actor: "DirtMedium", x: 128, y: 288, width: 128, height: 64 },
                {
                    macro: "Checkered",
                    actors: ["", "Flower"],
                    x: 128,
                    y: 304,
                    xnum: 8,
                    ynum: 2,
                    xwidth: 16,
                    yheight: 16,
                },
                {
                    macro: "Checkered",
                    actors: ["DirtClean", "DirtWhite"],
                    x: 128,
                    y: 352,
                    xnum: 4,
                    ynum: 2,
                },
                { actor: "DirtLight", x: 320, y: 352, width: 256, height: 64 },
                { actor: "FenceVertical", x: 320, y: 384, width: 96 },
                {
                    actor: "Sign",
                    x: 416,
                    y: 384,
                    dialog: "Oak %%%%%%%POKEMON%%%%%%% Research Lab",
                },
                { actor: "FenceVertical", x: 448, y: 384, width: 64 },
                { actor: "DirtMedium", x: 64, y: 416, width: 64, height: 128 },
                {
                    macro: "Water",
                    x: 128,
                    y: 416,
                    width: 128,
                    height: 128,
                    open: [false, false, true, false],
                },
                { actor: "DirtLight", x: 256, y: 416, width: 64, height: 128 },
                { actor: "DirtMedium", x: 320, y: 416, width: 192, height: 64 },
                {
                    actor: "FriendlyMan",
                    x: 352,
                    y: 416,
                    roaming: true,
                    dialog: [
                        "Technology is incredible!",
                        "You can now store and recall items and %%%%%%%POKEMON%%%%%%% as data via PC!",
                    ],
                },
                {
                    macro: "Checkered",
                    actors: ["", "Flower"],
                    x: 320,
                    y: 432,
                    xnum: 8,
                    ynum: 2,
                    xwidth: 16,
                    yheight: 16,
                },
                { actor: "DirtLight", x: 512, y: 416, width: 64, height: 128 },
                { actor: "DirtLight", x: 320, y: 480, width: 192, height: 64 },
                { actor: "FenceWide", x: 256, y: 512, width: 352 },
                { actor: "FenceWide", x: 32, y: 512 },
                { actor: "AreaSpawner", y: 512, map: "Route 21", area: "Land", direction: 2 },
            ],
        },
        "Player's House": {
            allowCycling: false,
            invisibleWallBorders: true,
            creation: [
                { actor: "WallIndoorHorizontalBands", width: 256 },
                { actor: "InvisibleWall", width: 256 },
                { actor: "FloorTiledDiagonal", y: 32, width: 256, height: 224 },
                { actor: "WindowBlinds", x: 96 },
                { actor: "WindowBlinds", x: 160 },
                { actor: "WindowBlinds", x: 224 },
                { actor: "Bookshelf", width: 64 },
                {
                    actor: "TelevisionMonitor",
                    x: 96,
                    y: 32,
                    dialogDirections: true,
                    dialog: [
                        "Oops, wrong side.",
                        "Oops, wrong side.",
                        [
                            "There's a movie on TV. Four boys are walking on railroad tracks.",
                            "I better go too.",
                        ],
                        "Oops, wrong side.",
                    ],
                },
                {
                    actor: "StairsUp",
                    x: 224,
                    y: 32,
                    entrance: "Player's House Floor 1 Stairs",
                    transport: { map: "Pallet Town", location: "Player's House Floor 2 Stairs" },
                },
                { actor: "Table2x3", x: 96, y: 128 },
                { actor: "Stool", x: 64, y: 128 },
                { actor: "Stool", x: 64, y: 160 },
                { actor: "Stool", x: 160, y: 128 },
                { actor: "Stool", x: 160, y: 160 },
                { actor: "FlowerVase", x: 116, y: 136 },
                {
                    actor: "Mother",
                    x: 160,
                    y: 128,
                    direction: 3,
                    directionPreferred: 12,
                    dialog: [
                        "MOM: Right. All boys leave home some day. It said so on TV.",
                        "PROF.OAK, next door, is looking for you.",
                    ],
                },
                {
                    actor: "DoormatDotted",
                    x: 64,
                    y: 224,
                    width: 64,
                    entrance: "Player's House Floor 1 Door",
                },
                {
                    actor: "HiddenTransporter",
                    x: 64,
                    y: 224,
                    width: 64,
                    transport: { map: "Pallet Town", location: "Player's House Door" },
                    requireDirection: 2,
                },
            ],
        },
        "Player's House Floor 2": {
            allowCycling: false,
            invisibleWallBorders: true,
            creation: [
                { actor: "WallIndoorHorizontalBands", width: 256 },
                { actor: "InvisibleWall", width: 256 },
                { actor: "FloorTiledDiagonal", y: 32, width: 256, height: 224 },
                {
                    actor: "ComputerDesk",
                    dialog: [
                        "We've watched while the stars burned out, and creation played in reverse.",
                        "The universe freezing in half light.",
                        "Once I thought to escape.",
                        "To end the end a master, step out of the path of collapse.",
                        "Escape would make us god.",
                        "Yet I cannot help remember one enigma.",
                        "A hybrid, elusive destroyer.",
                        "This is the only mystery I have not solved.",
                        "The only element unaccounted for.",
                        "Even S'bhuth is no more, he saved his entire race, but in the end, frozen by despair, he joined the chaos he sought to evade.",
                        "But you were dead a thousand times.",
                        "Hopeless encounters successfully won.",
                        "A man long dead, grafted to machines your builders did not understand.",
                        "You follow the path, fitting into an infinite pattern.",
                        "Yours to manipulate, to destroy and rebuild.",
                        "Now, in the quantum moment before the closure, when all become one.",
                        "One moment left.",
                        "One point of space and time.",
                        "I know who you are.",
                        "",
                        "You are destiny.",
                    ],
                },
                { actor: "Table2x2", x: 32, tolBottom: 0 },
                {
                    actor: "StairsDown",
                    x: 224,
                    y: 32,
                    entrance: "Player's House Floor 2 Stairs",
                    transport: { map: "Pallet Town", location: "Player's House Floor 1 Stairs" },
                },
                { actor: "WindowBlinds", x: 160 },
                { actor: "WindowBlinds", x: 224 },
                {
                    actor: "ConsoleAndController",
                    x: 96,
                    y: 128,
                    dialog: "%%%%%%%PLAYER%%%%%%% is playing the SNES! ...Okay! It's time to go!",
                },
                { actor: "TelevisionMonitor", x: 96, y: 96 },
                { actor: "BedSingle", y: 192 },
                { actor: "PottedPalmTree", x: 192, y: 192 },
            ],
        },
        "Rival's House": {
            allowCycling: false,
            invisibleWallBorders: true,
            creation: [
                { actor: "WallIndoorHorizontalBands", width: 256 },
                { actor: "InvisibleWall", width: 256 },
                { actor: "FloorTiledDiagonal", y: 32, width: 256, height: 224 },
                { actor: "Cabinet", width: 64 },
                { actor: "Painting", x: 96, dialog: "A TOWN MAP." },
                { actor: "Window", x: 160 },
                { actor: "Bookshelf", x: 224 },
                { actor: "Table2x3", x: 96, y: 96 },
                {
                    actor: "Book",
                    x: 96,
                    y: 96,
                    id: "Book",
                    dialog: "It's a big map! This is useful!",
                },
                {
                    actor: "Daisy",
                    x: 64,
                    y: 96,
                    direction: 1,
                    directionPreferred: 4,
                    dialog:
                        "Hi %%%%%%%PLAYER%%%%%%%! %%%%%%%RIVAL%%%%%%% is out at Grandpa's lab.",
                },
                { actor: "Stool", x: 64, y: 96 },
                { actor: "Stool", x: 64, y: 128 },
                { actor: "Stool", x: 160, y: 96 },
                { actor: "Stool", x: 160, y: 128 },
                { actor: "PottedPalmTree", y: 192 },
                { actor: "PottedPalmTree", x: 224, y: 192 },
                {
                    actor: "DoormatDotted",
                    x: 64,
                    y: 224,
                    width: 64,
                    entrance: "Rival's House Floor 1 Door",
                },
                {
                    actor: "HiddenTransporter",
                    x: 64,
                    y: 224,
                    width: 64,
                    transport: { map: "Pallet Town", location: "Rival's House Door" },
                    requireDirection: 2,
                },
            ],
        },
        "Oak's Lab": {
            allowCycling: false,
            theme: "Oak Research Lab",
            invisibleWallBorders: true,
            creation: [
                { actor: "WallIndoorLightWithDarkBottom", width: 256 },
                { actor: "InvisibleWall", width: 256 },
                { actor: "Table2x2", y: 16, width: 128 },
                {
                    actor: "LabComputer",
                    y: 32,
                    dialog: [
                        "There's an e-mail message here!",
                        "...",
                        "Calling all %%%%%%%POKEMON%%%%%%% trainers!",
                        "The elite trainers of %%%%%%%POKEMON%%%%%%% LEAGUE are ready to take on all comers!",
                        "Bring your best %%%%%%%POKEMON%%%%%%% and see how you rate as a trainer!",
                        "%%%%%%%POKEMON%%%%%%% LEAGUE HQ INDIGO PLATEAU",
                        "PS: PROF. OAK, please visit us! ...",
                    ],
                },
                {
                    actor: "Book",
                    x: 64,
                    y: 32,
                    id: "BookLeft",
                    dialog: "It's encyclopedia- like, but the pages are blank!",
                },
                {
                    actor: "Book",
                    x: 96,
                    y: 32,
                    id: "BookRight",
                    dialog: "It's encyclopedia- like, but the pages are blank!",
                },
                { actor: "FloorLinedHorizontal", y: 32, width: 320, height: 352 },
                { actor: "AsianScroll", x: 128, dialog: "Push START to open the MENU!" },
                {
                    actor: "AsianScroll",
                    x: 160,
                    dialog: "The SAVE option is on the MENU screen.",
                },
                { actor: "Oak", x: 160, y: 64, id: "Oak", hidden: true, nocollide: true },
                {
                    actor: "Rival",
                    x: 128,
                    y: 96,
                    id: "Rival",
                    dialog: "Yo %%%%%%%PLAYER%%%%%%%! Gramps isn't around!",
                },
                { actor: "Table3x1", x: 192, y: 96 },
                {
                    actor: "Pokeball",
                    x: 192,
                    y: 96,
                    id: "PokeballCHARMANDER",
                    action: "cutscene",
                    cutscene: "OakIntroPokemonChoice",
                    pokemon: ["C", "H", "A", "R", "M", "A", "N", "D", "E", "R"],
                    description: "fire",
                },
                {
                    actor: "Pokeball",
                    x: 224,
                    y: 96,
                    id: "PokeballSQUIRTLE",
                    action: "cutscene",
                    cutscene: "OakIntroPokemonChoice",
                    pokemon: ["S", "Q", "U", "I", "R", "T", "L", "E"],
                    description: "water",
                },
                {
                    actor: "Pokeball",
                    x: 256,
                    y: 96,
                    id: "PokeballBULBASAUR",
                    action: "cutscene",
                    cutscene: "OakIntroPokemonChoice",
                    pokemon: ["B", "U", "L", "B", "A", "S", "A", "U", "R"],
                    description: "plant",
                },
                { actor: "Bookshelf", x: 192, width: 128 },
                { actor: "Bookshelf", y: 192, width: 128 },
                { actor: "Bookshelf", x: 192, y: 192, width: 128 },
                {
                    actor: "MenuTriggerer",
                    x: 128,
                    y: 224,
                    width: 128,
                    id: "OakBlocker",
                    pushSteps: [{ direction: 0, blocks: 1 }],
                    keepAlive: true,
                    nocollide: true,
                    dialog: "OAK: Hey! Don't go away yet!",
                },
                {
                    actor: "CutsceneTriggerer",
                    x: 128,
                    y: 192,
                    width: 128,
                    id: "RivalBlocker",
                    cutscene: "OakIntroRivalBattle",
                    routine: "Approach",
                    nocollide: true,
                },
                {
                    actor: "Lady",
                    x: 32,
                    y: 288,
                    dialog: [
                        "PROF.OAK is the authority on %%%%%%%POKEMON%%%%%%%!",
                        "Many %%%%%%%POKEMON%%%%%%% trainers hold him in high regard!",
                    ],
                    roaming: true,
                    roamingDirections: [0, 8],
                },
                {
                    actor: "Scientist",
                    x: 64,
                    y: 320,
                    name: "Scientist One",
                    dialog: "I study %%%%%%%POKEMON%%%%%%% as PROF.OAK's aide.",
                    roaming: true,
                    roamingDirections: [],
                },
                {
                    actor: "Scientist",
                    x: 256,
                    y: 320,
                    name: "Scientist Two",
                    dialog: "I study %%%%%%%POKEMON%%%%%%% as PROF.OAK's aide.",
                    roaming: true,
                    roamingDirections: [],
                },
                { actor: "Doormat", x: 128, y: 352, id: "DoormatLeft" },
                {
                    actor: "Doormat",
                    x: 160,
                    y: 352,
                    id: "DoormatRight",
                    entrance: "Oak's Lab Floor 1 Door",
                },
                {
                    actor: "HiddenTransporter",
                    x: 128,
                    y: 352,
                    width: 64,
                    transport: { map: "Pallet Town", location: "Oak's Lab Door" },
                    requireDirection: 2,
                },
            ],
        },
    },
};
