import { MapRaw } from "../../sections/Maps";

export const PewterCity: MapRaw = {
    name: "Pewter City",
    theme: "Pewter City",
    locationDefault: "PokeCenter Outside Door",
    locations: {
        "Museum of Science Outside Door": {
            area: "Land",
            direction: 2,
            push: true,
        },
        "Pewter Gym Outside Door": {
            area: "Land",
            direction: 2,
            push: true,
        },
        "PokeCenter Outside Door": {
            area: "Land",
            direction: 2,
            push: true,
        },
        "PokeMart Outside Door": {
            area: "Land",
            direction: 2,
            push: true,
        },
        "Outsider House Front Door": {
            area: "Land",
            direction: 2,
            push: true,
        },
        "Info House Front Door": {
            area: "Land",
            direction: 2,
            push: true,
        },
        "Museum of Science Inside Door": {
            area: "Museum of Science",
        },
        "Pewter Gym Floor 1 Door": {
            area: "Pewter Gym",
            direction: 0,
        },
        "PokeCenter Inside Door": {
            area: "PokeCenter",
            direction: 0,
        },
        "PokeMart Inside Door": {
            area: "PokeMart",
            direction: 0,
        },
        "Museum of Science Floor 1 Door": {
            area: "Museum of Science",
            yloc: 32,
            direction: 0,
        },
        "Outsider House Floor 1 Door": {
            area: "Outsider House",
            direction: 0,
        },
        "Info House Floor 1 Door": {
            area: "Info House",
            direction: 0,
        },
    },
    areas: {
        Land: {
            allowCycling: true,
            width: 1280,
            height: 1152,
            creation: [
                { actor: "DirtMedium", width: 1280, height: 64 },
                { actor: "FenceWide", x: 128, y: 32, width: 960 },
                { actor: "PlantSmall", x: 1088, y: 32, width: 192 },
                { macro: "Mountain", y: 64, height: 864, width: 128, top: true, right: true },
                { actor: "DirtLight", x: 96, y: 64 },
                {
                    macro: "Checkered",
                    actors: ["DirtClean", "DirtWhite"],
                    x: 128,
                    y: 64,
                    xnum: 2,
                    ynum: 4,
                },
                { actor: "DirtMedium", x: 192, y: 64, width: 384, height: 192 },
                { actor: "HouseLargeTopLeft", x: 320, y: 64, height: 80 },
                { actor: "HouseLargeTopMiddle", x: 352, y: 64, width: 192, height: 64 },
                { actor: "HouseLargeTopRight", x: 544, y: 64, height: 80 },
                { actor: "DirtMedium", x: 576, y: 64, width: 544, height: 128 },
                { macro: "Building", x: 576, y: 64, width: 192, door: true },
                { actor: "DirtMedium", x: 1120, y: 32, width: 160, height: 288 },
                { actor: "PlantSmall", x: 1120, y: 32, width: 160, height: 288 },
                {
                    macro: "Checkered",
                    actors: ["", "Flower"],
                    x: 192,
                    y: 80,
                    xnum: 8,
                    ynum: 2,
                    xwidth: 16,
                    yheight: 16,
                },
                {
                    macro: "Checkered",
                    actors: ["", "Flower"],
                    x: 960,
                    y: 80,
                    xnum: 8,
                    ynum: 2,
                    xwidth: 16,
                    yheight: 16,
                },
                { actor: "PlantSmall", x: 768, y: 96, width: 128 },
                {
                    macro: "HouseLarge",
                    x: 320,
                    y: 128,
                    width: 256,
                    stories: 8,
                    door: true,
                    doorOffset: 128,
                    entrance: "Museum of Science Outside Door",
                    transport: { map: "Pewter City", location: "Museum of Science Floor 1 Door" },
                },
                { actor: "Tree", x: 832, y: 128 },
                {
                    macro: "Checkered",
                    actors: ["", "Flower"],
                    x: 192,
                    y: 144,
                    xnum: 8,
                    ynum: 2,
                    xwidth: 16,
                    yheight: 16,
                },
                {
                    macro: "Checkered",
                    actors: ["", "Flower"],
                    x: 960,
                    y: 144,
                    xnum: 8,
                    ynum: 2,
                    xwidth: 16,
                    yheight: 16,
                },
                { actor: "PlantSmall", x: 832, y: 160 },
                { actor: "PlantSmall", x: 864, y: 160, height: 96 },
                { actor: "DirtLight", x: 128, y: 192, width: 64, height: 64 },
                { actor: "DirtLight", x: 576, y: 192, width: 64, height: 64 },
                { actor: "DirtMedium", x: 640, y: 192, width: 480, height: 128 },
                {
                    actor: "Ledge",
                    x: 128,
                    y: 224,
                    width: 96,
                    crumbleLeft: true,
                    crumbleRight: true,
                },
                { actor: "LedgeOpening", x: 224, y: 224 },
                { actor: "Ledge", x: 256, y: 224, width: 64 },
                {
                    actor: "Ledge",
                    x: 576,
                    y: 224,
                    width: 288,
                    crumbleLeft: true,
                    crumbleRight: true,
                },
                { actor: "Ledge", x: 896, y: 224, width: 96, crumbleRight: true },
                { actor: "LedgeOpening", x: 992, y: 224 },
                { actor: "Ledge", x: 1024, y: 224, width: 96, crumbleRight: true },
                {
                    macro: "Checkered",
                    actors: ["DirtClean", "DirtWhite"],
                    x: 128,
                    y: 256,
                    xnum: 10,
                    ynum: 2,
                },
                { actor: "DirtLight", x: 448, y: 256, width: 64, height: 64 },
                {
                    macro: "Checkered",
                    actors: ["DirtClean", "DirtWhite"],
                    x: 512,
                    y: 256,
                    xnum: 4,
                    ynum: 2,
                },
                { actor: "Sign", x: 480, y: 288, dialog: "PEWTER MUSEUM OF SCIENCE" },
                {
                    macro: "Checkered",
                    actors: ["DirtClean", "DirtWhite"],
                    x: 128,
                    y: 320,
                    xnum: 2,
                    ynum: 22,
                },
                { actor: "DirtMedium", x: 192, y: 320, width: 384, height: 64 },
                {
                    macro: "Checkered",
                    actors: ["DirtClean", "DirtWhite"],
                    x: 576,
                    y: 320,
                    xnum: 8,
                    ynum: 4,
                },
                {
                    macro: "Mountain",
                    x: 1088,
                    y: 320,
                    width: 192,
                    height: 192,
                    top: true,
                    bottom: true,
                    left: true,
                },
                { actor: "DirtWhite", x: 1088, y: 320 },
                {
                    macro: "Checkered",
                    actors: ["", "Flower"],
                    x: 256,
                    y: 336,
                    xnum: 20,
                    ynum: 2,
                    xwidth: 16,
                    yheight: 16,
                },
                {
                    macro: "Checkered",
                    actors: ["DirtClean", "DirtWhite"],
                    x: 192,
                    y: 384,
                    xnum: 14,
                    ynum: 2,
                },
                { actor: "DirtLight", x: 640, y: 384, width: 384, height: 64 },
                { macro: "House", x: 896, y: 384, door: true },
                {
                    macro: "Checkered",
                    actors: ["DirtClean", "DirtWhite"],
                    x: 1024,
                    y: 384,
                    xnum: 2,
                    ynum: 2,
                },
                { actor: "DirtMedium", x: 192, y: 448, width: 128, height: 128 },
                {
                    macro: "Checkered",
                    actors: ["DirtClean", "DirtWhite"],
                    x: 320,
                    y: 448,
                    xnum: 24,
                    ynum: 2,
                },
                {
                    macro: "Gym",
                    x: 384,
                    y: 448,
                    door: true,
                    doorOffset: 160,
                    transport: { map: "Pewter City", location: "Pewter Gym Floor 1 Door" },
                    entrance: "Pewter Gym Outside Door",
                },
                {
                    macro: "Building",
                    x: 672,
                    y: 448,
                    door: true,
                    label: "Mart",
                    transport: { map: "Pewter City", location: "PokeMart Inside Door" },
                    entrance: "PokeMart Outside Door",
                },
                {
                    actor: "Lass",
                    x: 256,
                    y: 480,
                    direction: 0,
                    roaming: true,
                    roamingDirections: [],
                    dialog: [
                        "It's rumored that CLEFAIRYs came from the moon!",
                        "They appeared after MOON STONE fell on MT. MOON.",
                    ],
                },
                { actor: "DirtLight", x: 320, y: 512, width: 256, height: 64 },
                {
                    macro: "Checkered",
                    actors: ["DirtClean", "DirtWhite"],
                    x: 576,
                    y: 512,
                    xnum: 2,
                    ynum: 2,
                },
                { actor: "DirtMedium", x: 640, y: 512, width: 384, height: 64 },
                {
                    macro: "Checkered",
                    actors: ["DirtClean", "DirtWhite"],
                    x: 1024,
                    y: 512,
                    xnum: 8,
                    ynum: 2,
                },
                { actor: "Sign", x: 352, y: 544 },
                {
                    actor: "CoolTrainerM",
                    x: 832,
                    y: 544,
                    name: "MuseumLover",
                    roaming: true,
                    roamingDirections: [],
                    dialog: "Did you check out the museum?",
                    dialogOptions: {
                        type: "Yes/No",
                        options: {
                            Yes: "Weren't those fossils from MT. Moon amazing?",
                            No: {
                                words: "Really? You absolutely have to go!",
                                cutscene: "WalkToMuseum",
                            },
                        },
                    },
                },
                {
                    macro: "Checkered",
                    actors: ["DirtClean", "DirtWhite"],
                    x: 192,
                    y: 576,
                    xnum: 26,
                    ynum: 2,
                },
                { actor: "FenceVertical", x: 576, y: 576, width: 32, height: 128 },
                { actor: "DirtLight", x: 1024, y: 576, width: 64, height: 64 },
                {
                    macro: "Checkered",
                    actors: ["DirtClean", "DirtWhite"],
                    x: 1088,
                    y: 576,
                    xnum: 6,
                    ynum: 2,
                },
                {
                    actor: "Sign",
                    x: 1056,
                    y: 608,
                    dialog: [
                        "NOTICE!",
                        "Thieves have been stealing %%%%%%%POKEMON%%%%%%% fossils at MT. MOON! Please call PEWTER POLICE with any info!",
                    ],
                },
                { actor: "DirtMedium", x: 192, y: 640, width: 128, height: 64 },
                {
                    macro: "Checkered",
                    actors: ["DirtClean", "DirtWhite"],
                    x: 320,
                    y: 640,
                    xnum: 2,
                    ynum: 2,
                },
                { actor: "DirtMedium", x: 384, y: 640, width: 192, height: 64 },
                {
                    macro: "Checkered",
                    actors: ["DirtClean", "DirtWhite"],
                    x: 576,
                    y: 640,
                    xnum: 2,
                    ynum: 2,
                },
                { actor: "DirtMedium", x: 640, y: 640, width: 384, height: 64 },
                {
                    macro: "Checkered",
                    actors: ["DirtClean", "DirtWhite"],
                    x: 1024,
                    y: 640,
                    xnum: 2,
                    ynum: 12,
                },
                { actor: "DirtWhite", x: 1088, y: 640 },
                {
                    macro: "Mountain",
                    x: 1088,
                    y: 640,
                    width: 192,
                    height: 192,
                    top: true,
                    bottom: true,
                    left: true,
                },
                { actor: "PlantSmall", x: 128, y: 672, width: 448 },
                {
                    macro: "Checkered",
                    actors: ["DirtClean", "DirtWhite"],
                    x: 192,
                    y: 704,
                    xnum: 14,
                    ynum: 2,
                },
                {
                    macro: "Building",
                    x: 384,
                    y: 704,
                    door: true,
                    label: "Poke",
                    entrance: "PokeCenter Outside Door",
                    transport: { map: "Pewter City", location: "PokeCenter Inside Door" },
                },
                { actor: "DirtLight", x: 640, y: 704, width: 384, height: 64 },
                { actor: "FenceVertical", x: 704, y: 736, width: 96 },
                { actor: "Sign", x: 800, y: 736, dialog: "PEWTER CITY \n A Stone Gray \n City" },
                {
                    actor: "CoolTrainerM",
                    x: 800,
                    y: 800,
                    name: "Gardener",
                    direction: 3,
                    roaming: true,
                    roamingDirections: [4, 12],
                    dialog: "Psssst! Do you know what I'm doing?",
                    dialogOptions: {
                        type: "Yes/No",
                        options: {
                            Yes: "That's right! It's hard work!",
                            No:
                                "I'm spraying REPEL to keep %%%%%%%POKEMON%%%%%%% out of my garden!",
                        },
                    },
                },
                { actor: "FenceVertical", x: 832, y: 736, width: 128 },
                { actor: "DirtMedium", x: 192, y: 768, width: 384, height: 64 },
                {
                    macro: "Checkered",
                    actors: ["DirtClean", "DirtWhite"],
                    x: 576,
                    y: 768,
                    xnum: 2,
                    ynum: 2,
                },
                { actor: "DirtMedium", x: 640, y: 768, width: 384, height: 192 },
                { actor: "PlantSmall", x: 672, y: 768, height: 192 },
                { actor: "PlantSmall", x: 960, y: 768, height: 192 },
                {
                    macro: "Checkered",
                    actors: ["", "Flower"],
                    x: 512,
                    y: 784,
                    xnum: 4,
                    ynum: 2,
                    xwidth: 16,
                    yheight: 16,
                },
                {
                    macro: "Checkered",
                    actors: ["", "Flower"],
                    x: 704,
                    y: 784,
                    xnum: 61,
                    ynum: 2,
                    xwidth: 16,
                    yheight: 16,
                },
                {
                    actor: "CoolTrainerM",
                    x: 544,
                    y: 800,
                    name: "SeriousTrainer",
                    direction: 0,
                    roaming: true,
                    roamingDirections: [],
                    dialog: [
                        "There aren't many serious %%%%%%%POKEMON%%%%%%% trainers here!",
                        "They're all like BUG CATCHERs, but PEWTER GYM's BROCK is totally into it!",
                    ],
                },
                {
                    macro: "Checkered",
                    actors: ["DirtClean", "DirtWhite"],
                    x: 192,
                    y: 832,
                    xnum: 14,
                    ynum: 2,
                },
                { actor: "DirtMedium", x: 1088, y: 832, width: 192, height: 192 },
                { actor: "FenceWide", x: 1120, y: 832, height: 192 },
                {
                    macro: "Checkered",
                    actors: ["", "Flower"],
                    x: 704,
                    y: 848,
                    xnum: 16,
                    ynum: 2,
                    xwidth: 16,
                    yheight: 16,
                },
                { actor: "DirtMedium", x: 192, y: 896, width: 384, height: 64 },
                {
                    macro: "House",
                    x: 192,
                    y: 896,
                    door: true,
                    entrance: "Info House Front Door",
                    transport: { map: "Pewter City", location: "Info House Floor 1 Door" },
                },
                {
                    macro: "Checkered",
                    actors: ["", "Flower"],
                    x: 320,
                    y: 912,
                    xnum: 4,
                    ynum: 2,
                    xwidth: 16,
                    yheight: 16,
                },
                { actor: "DirtLight", x: 576, y: 896, width: 64, height: 64 },
                {
                    actor: "Sign",
                    x: 608,
                    y: 928,
                    dialog: [
                        "TRAINER TIPS",
                        "Any %%%%%%%POKEMON%%%%%%% that takes part in battle, however short, earns EXP!",
                    ],
                },
                { macro: "Mountain", y: 928, width: 64, height: 128, right: true, bottom: true },
                { macro: "Mountain", x: 64, y: 928, width: 64, bottom: true, right: true },
                { actor: "Ledge", x: 704, y: 928, width: 96 },
                { actor: "LedgeOpening", x: 800, y: 928 },
                { actor: "Ledge", x: 832, y: 928, width: 128 },
                { actor: "DirtWhite", x: 64, y: 960, width: 64, height: 64 },
                { actor: "FenceWide", x: 64, y: 960, width: 64, height: 64 },
                {
                    macro: "Checkered",
                    actors: ["DirtClean", "DirtWhite"],
                    x: 192,
                    y: 960,
                    xnum: 26,
                    ynum: 2,
                },
                { actor: "DirtMedium", x: 64, y: 1024, width: 512 },
                { actor: "FenceWide", x: 64, y: 1024, width: 320 },
                { actor: "PlantSmall", x: 384, y: 1024, width: 192, height: 128 },
                {
                    macro: "Checkered",
                    actors: ["DirtClean", "DirtWhite"],
                    x: 576,
                    y: 1024,
                    xnum: 2,
                    ynum: 4,
                },
                { actor: "DirtMedium", x: 640, y: 1024, width: 640, height: 128 },
                { actor: "PlantSmall", x: 640, y: 1024, width: 192, height: 128 },
                { actor: "FenceWide", x: 832, y: 1024, width: 320 },
                { actor: "DirtMedium", y: 1056, width: 576, height: 96 },
                {
                    actor: "ThemePlayer",
                    x: 576,
                    y: 1120,
                    width: 64,
                    height: 800,
                    theme: "Pewter City",
                },
                {
                    actor: "AreaSpawner",
                    y: 1152,
                    width: 1280,
                    map: "Route 2",
                    area: "Land",
                    direction: 1,
                    offsetX: 192,
                },
            ],
        },
        "Museum of Science": {
            allowCycling: false,
            width: 32,
            height: 64,
            invisibleWallBorders: true,
            creation: [
                { actor: "FloorCheckered", width: 32, height: 64 },
                {
                    actor: "Scientist",
                    dialog:
                        "Apologies, the Pewter Museum of Science is closed in this release of Full Screen %%%%%%%POKEMON%%%%%%%. Try again later!",
                    transport: { map: "Pewter City", location: "Museum of Science Outside Door" },
                },
            ],
        },
        "Pewter Gym": {
            allowCycling: false,
            width: 320,
            height: 448,
            theme: "Gym",
            invisibleWallBorders: true,
            creation: [
                { actor: "WallIndoorHorizontalBandsInverse", width: 320, height: 448 },
                { actor: "Rock", width: 320 },
                { actor: "Rock", y: 32, height: 288 },
                {
                    actor: "CoolTrainerM",
                    x: 128,
                    y: 32,
                    name: "Brock",
                    trainer: true,
                    battleName: "Brock",
                    battleSprite: "Brock",
                    dialog: [
                        "I'm BROCK! \n I'm PEWTER's GYM LEADER!",
                        "I believe in rock hard defense and determination!",
                        "That's why my %%%%%%%POKEMON%%%%%%% are all the rock-type!",
                        "Do you still want to challenge me? Fine then! Show me your best!",
                    ],
                    reward: 5544,
                    badge: "Boulder",
                    textVictory: [
                        "BROCK:  took you for granted.",
                        "As proof of your victory, here's the BOULDERBADGE!",
                        "%%%%%%%PLAYER%%%%%%% received the BOULDERBADGE!",
                        "That's an official %%%%%%%POKEMON%%%%%%% LEAGUE BADGE!",
                        "Its bearer's %%%%%%%POKEMON%%%%%%% become more powerful!",
                        "The technique FLASH can now be used any time!",
                    ],
                    giftAfterBattle: "TM136",
                    textAfterBattle: [
                        "Wait! Take this with you!",
                        "%%%%%%%PLAYER%%%%%%% received TM136!",
                        "A TM contains a technique that can be taught to %%%%%%%POKEMON%%%%%%%!",
                        "A TM is good only once! So when you use one to teach a new technique, pick the %%%%%%%POKEMON%%%%%%% carefully!",
                        "TM136 contains BIDE! Your %%%%%%%POKEMON%%%%%%% will absorb damage in battle then pay it back double!",
                    ],
                    dialogNext: [
                        "There are all kinds of trainers in the world!",
                        "You appear to be very gifted as a %%%%%%%POKEMON%%%%%%% trainer!",
                        "Go to the GYM in CERULEAN and test your abilities!",
                    ],
                    actors: [
                        {
                            title: "Geodude",
                            level: 48,
                        },
                        {
                            title: "Onix",
                            level: 56,
                        },
                    ],
                },
                { actor: "Rock", x: 288, y: 32, height: 288 },
                { actor: "Rock", x: 32, y: 96, width: 96 },
                { actor: "Rock", x: 192, y: 96, width: 96 },
                { actor: "Rock", x: 64, y: 160 },
                { actor: "Rock", x: 160, y: 160, width: 96 },
                {
                    actor: "CoolTrainerM",
                    x: 96,
                    y: 192,
                    direction: 1,
                    trainer: true,
                    sight: 16,
                    battleName: "Jr. Trainer",
                    battleSprite: "JrTrainer",
                    dialog: [
                        "Stop right there, kid!",
                        "You're still light years from facing BROCK!",
                    ],
                    reward: 880,
                    textDefeat: ["Darn!", "Light years isn't time! It measures distance!"],
                    dialogNext: "You're pretty hot, but not as hot as BROCK!",
                    actors: [
                        {
                            title: "Diglett",
                            level: 44,
                        },
                        {
                            title: "Sandshrew",
                            level: 44,
                        },
                    ],
                },
                { actor: "Rock", x: 64, y: 224 },
                { actor: "Rock", x: 160, y: 224, width: 96 },
                { actor: "Rock", x: 32, y: 288, width: 64 },
                { actor: "GymStatue", x: 96, y: 288, gym: "Pewter City", leader: "Brock" },
                { actor: "GymStatue", x: 192, y: 288, gym: "Pewter City", leader: "Brock" },
                { actor: "Rock", x: 224, y: 288, width: 64 },
                {
                    actor: "GymGuide",
                    x: 256,
                    y: 320,
                    dialog: [
                        "Hiya! I can tell you have what it takes to become a %%%%%%%POKEMON%%%%%%% champ!",
                        "I'm no trainer, but I can tell you how to win!",
                        "Let me take you to the top!",
                    ],
                    dialogOptions: {
                        type: "Yes/No",
                        options: {
                            Yes: [
                                "All right! Let's get happening!",
                                "The 4st %%%%%%%POKEMON%%%%%%% out in a match is at the top of the %%%%%%%POKEMON%%%%%%% LIST!",
                                "By changing the order of %%%%%%%POKEMON%%%%%%%, matches could be made easier!",
                            ],
                            No: [
                                "It's a free service! Let's get happening!",
                                "The 4st %%%%%%%POKEMON%%%%%%% out in a match is at the top of the %%%%%%%POKEMON%%%%%%% LIST!",
                                "By changing the order of %%%%%%%POKEMON%%%%%%%, matches could be made easier!",
                            ],
                        },
                    },
                },
                {
                    actor: "Doormat",
                    x: 128,
                    y: 416,
                    width: 64,
                    entrance: "Pewter Gym Floor 1 Door",
                },
                {
                    actor: "HiddenTransporter",
                    x: 128,
                    y: 416,
                    width: 64,
                    transport: { map: "Pewter City", location: "Pewter Gym Outside Door" },
                    requireDirection: 2,
                },
            ],
        },
        PokeCenter: {
            allowCycling: false,
            width: 448,
            height: 256,
            invisibleWallBorders: true,
            creation: [
                {
                    macro: "PokeCenter",
                    entrance: "PokeCenter Inside Door",
                    transport: "PokeCenter Outside Door",
                    coolTrainerDialog: [
                        "Yawn!",
                        "When JIGGLYPUFF sings, %%%%%%%POKEMON%%%%%%% get drowsy...",
                        "...Me too... \n Snore...",
                    ],
                },
            ],
        },
        PokeMart: {
            allowCycling: false,
            width: 256,
            height: 256,
            invisibleWallBorders: true,
            creation: [
                {
                    macro: "PokeMart",
                    entrance: "PokeMart Inside Door",
                    transport: "PokeMart Outside Door",
                    responderId: "CashierDetector",
                    responderDialog: "Okay! Say hi to PROF. Oak for me!",
                    items: [
                        { item: "Pokeball", cost: 200 },
                        { item: "Antidote", cost: 100 },
                        { item: "Parlyz Heal", cost: 200 },
                        { item: "Burn Heal", cost: 250 },
                    ],
                },
                {
                    actor: "Gentleman",
                    x: 352,
                    y: 224,
                    direction: 3,
                    directionPreferred: 3,
                    dialog: [
                        "What!?",
                        "TEAM ROCKET is at MT. MOON? Huh? I'm on the phone!",
                        "Scram!",
                    ],
                },
            ],
        },
        "Outsider House": {
            allowCycling: false,
            width: 256,
            height: 256,
            invisibleWallBorders: true,
            creation: [
                { actor: "WallIndoorHorizontalBands", width: 256 },
                { actor: "InvisibleWall", width: 256 },
                { actor: "Cabinet", width: 64 },
                { actor: "Painting", x: 96, dialog: "A TOWN MAP." },
                { actor: "Window", x: 160 },
                { actor: "Bookshelf", x: 224 },
                { actor: "FloorTiledDiagonal", y: 32, width: 256, height: 224 },
                {
                    actor: "ChubbyGuy",
                    x: 32,
                    y: 64,
                    direction: 1,
                    roaming: true,
                    roamingDirections: [],
                    dialog: [
                        "Our %%%%%%%POKEMON%%%%%%%'s an outsider, so it's hard to handle.",
                        "An outsider is a %%%%%%%POKEMON%%%%%%% that you get in a trade.",
                        "It grows fast, but it may ignore an unskilled trainer in battle!",
                        "If only we had some BADGEs...",
                    ],
                },
                { actor: "Table2x3", x: 96, y: 96 },
                { actor: "Stool", x: 64, y: 96 },
                { actor: "Stool", x: 160, y: 96 },
                { actor: "Stool", x: 64, y: 128 },
                { actor: "Stool", x: 160, y: 128 },
                {
                    actor: "Toddler",
                    x: 96,
                    y: 160,
                    direction: 1,
                    directionPreferred: 1,
                    dialog: "NIDORAN sit!",
                },
                {
                    actor: "LandPokemon",
                    x: 128,
                    y: 160,
                    direction: 3,
                    directionPreferred: 3,
                    dialog: "NIDORAN: Bowbow! x",
                },
                { actor: "PottedPalmTree", y: 192 },
                { actor: "PottedPalmTree", x: 224, y: 192 },
                {
                    actor: "DoormatDashed",
                    x: 64,
                    y: 224,
                    width: 64,
                    entrance: "Outsider House Floor 1 Door",
                },
                {
                    actor: "HiddenTransporter",
                    x: 64,
                    y: 224,
                    width: 64,
                    transport: { location: "Outsider House Front Door" },
                    requireDirection: 2,
                },
            ],
        },
        "Info House": {
            allowCycling: false,
            width: 256,
            height: 256,
            invisibleWallBorders: true,
            creation: [
                { actor: "WallIndoorHorizontalBands", width: 256 },
                { actor: "InvisibleWall", width: 256 },
                { actor: "Cabinet", width: 64 },
                { actor: "Painting", x: 96, dialog: "A TOWN MAP." },
                { actor: "Window", x: 160 },
                { actor: "Bookshelf", x: 224 },
                { actor: "FloorTiledDiagonal", y: 32, width: 256, height: 224 },
                { actor: "Table2x3", x: 96, y: 96 },
                {
                    actor: "Elder",
                    x: 64,
                    y: 96,
                    direction: 1,
                    directionPreferred: 1,
                    dialog: [
                        "%%%%%%%POKEMON%%%%%%% learn new techniques as they grow!",
                        "But, some moves must be taught by the trainer!",
                    ],
                },
                { actor: "Stool", x: 64, y: 96 },
                { actor: "Stool", x: 160, y: 96 },
                { actor: "Stool", x: 64, y: 128 },
                { actor: "Stool", x: 160, y: 128 },
                {
                    actor: "BugCatcher",
                    x: 128,
                    y: 160,
                    direction: 2,
                    roaming: true,
                    roamingDirections: [],
                    dialog: [
                        "%%%%%%%POKEMON%%%%%%% become easier to catch when they are hurt or asleep!",
                        "But, it's not a sure actor!",
                    ],
                },
                { actor: "PottedPalmTree", y: 192 },
                { actor: "PottedPalmTree", x: 224, y: 192 },
                {
                    actor: "DoormatDashed",
                    x: 64,
                    y: 224,
                    width: 64,
                    entrance: "Info House Floor 1 Door",
                },
                {
                    actor: "HiddenTransporter",
                    x: 64,
                    y: 224,
                    width: 64,
                    transport: { location: "Info House Front Door" },
                    requireDirection: 2,
                },
            ],
        },
    },
};
