import { MapRaw } from "../../sections/Maps";

export const Route1: MapRaw = {
    name: "Route 1",
    theme: "Viridian City from Pallet Town",
    locationDefault: "Top Path",
    locations: {
        "Top Path": {
            area: "Land",
            xloc: 320,
        },
        "Bottom Path": {
            area: "Land",
            xloc: 320,
            yloc: 1152,
        },
    },
    areas: {
        Land: {
            allowCycling: true,
            width: 640,
            height: 1184,
            wildPokemon: {
                grass: [
                    {
                        title: "PIDGEY".split(""),
                        levels: [2, 3, 4, 5],
                        rate: 0.55,
                    },
                    {
                        title: "RATTATA".split(""),
                        levels: [2, 3, 4],
                        rate: 0.45,
                    },
                ],
            },
            creation: [
                {
                    actor: "AreaSpawner",
                    width: 640,
                    map: "Viridian City",
                    area: "Land",
                    direction: 0,
                    offsetX: -320,
                },
                {
                    actor: "ThemePlayer",
                    x: 320,
                    width: 64,
                    theme: "Viridian City from Pallet Town",
                },
                { actor: "DirtMedium", width: 128, height: 1184 },
                { actor: "FenceWide", x: 96, height: 192 },
                { actor: "DirtMedium", x: 96, width: 224, height: 320 },
                { actor: "FenceWide", x: 288 },
                { actor: "DirtLight", x: 320, width: 64, height: 128 },
                { actor: "FenceWide", x: 384 },
                { actor: "DirtMedium", x: 384, width: 192, height: 128 },
                { actor: "DirtMedium", x: 576, width: 64, height: 1184 },
                { actor: "FenceWide", x: 576, height: 192 },
                { actor: "FenceWide", x: 128, y: 32, width: 192 },
                { actor: "FenceWide", x: 384, y: 32, width: 192 },
                {
                    macro: "Checkered",
                    actors: ["", "Flower"],
                    x: 512,
                    y: 80,
                    xnum: 4,
                    ynum: 2,
                    xwidth: 16,
                    yheight: 16,
                },
                { actor: "DirtLight", x: 320, y: 128, width: 256, height: 64 },
                { actor: "PlantSmall", x: 288, y: 128, height: 192 },
                { actor: "Ledge", x: 128, y: 160, width: 160, crumbleRight: true },
                { actor: "Ledge", x: 320, y: 160, width: 128, jagged: true },
                { actor: "PlantSmall", x: 96, y: 192, height: 256 },
                { actor: "DirtMedium", x: 320, y: 192, width: 256, height: 128 },
                { actor: "Grass", x: 320, y: 192, width: 256, height: 128 },
                { actor: "PlantSmall", x: 576, y: 192, height: 256 },
                {
                    macro: "Checkered",
                    actors: ["", "Flower"],
                    x: 128,
                    y: 208,
                    xnum: 8,
                    ynum: 2,
                    xwidth: 16,
                    yheight: 16,
                },
                { actor: "Ledge", x: 128, y: 288, width: 160, crumbleRight: true },
                { actor: "DirtMedium", x: 128, y: 320, width: 256, height: 192 },
                { actor: "DirtLight", x: 384, y: 320, width: 192, height: 64 },
                {
                    macro: "Checkered",
                    actors: ["", "Flower"],
                    x: 192,
                    y: 336,
                    xnum: 8,
                    ynum: 2,
                    xwidth: 16,
                    yheight: 16,
                },
                {
                    macro: "Checkered",
                    actors: ["DirtClean", "DirtWhite"],
                    x: 384,
                    y: 384,
                    xnum: 2,
                    ynum: 2,
                },
                { actor: "DirtMedium", x: 448, y: 384, width: 128, height: 192 },
                { actor: "Grass", x: 448, y: 384, width: 128, height: 128 },
                { actor: "PlantSmall", x: 128, y: 416, width: 64 },
                { actor: "PlantSmall", x: 320, y: 416, width: 128 },
                {
                    actor: "BugCatcher",
                    x: 480,
                    y: 416,
                    direction: 3,
                    roaming: true,
                    roamingDirections: [4, 12],
                    name: "LedgeAdvertiser",
                    dialog: [
                        "See those ledges along the road?",
                        "It's a bit scary, but you can jump from them.",
                        "You can get back to Pallet Town quicker that way.",
                    ],
                },
                { actor: "Ledge", x: 192, y: 416, width: 128 },
                { actor: "FenceWide", x: 96, y: 448, height: 448 },
                { actor: "FenceWide", x: 576, y: 448, height: 448 },
                { actor: "DirtLight", x: 384, y: 448, width: 64, height: 64 },
                {
                    macro: "Checkered",
                    actors: ["", "Flower"],
                    x: 256,
                    y: 464,
                    xnum: 8,
                    ynum: 2,
                    xwidth: 16,
                    yheight: 16,
                },
                { actor: "DirtMedium", x: 128, y: 512, width: 64, height: 192 },
                { actor: "DirtLight", x: 192, y: 512, width: 256, height: 64 },
                {
                    macro: "Checkered",
                    actors: ["", "Flower"],
                    x: 448,
                    y: 528,
                    xnum: 8,
                    ynum: 2,
                    xwidth: 16,
                    yheight: 16,
                },
                { actor: "DirtLight", x: 192, y: 576, width: 64, height: 64 },
                { actor: "DirtMedium", x: 256, y: 576, width: 320, height: 64 },
                { actor: "Ledge", x: 128, y: 608, width: 32 },
                { actor: "LedgeOpening", x: 160, y: 608, width: 32 },
                {
                    actor: "Ledge",
                    x: 192,
                    y: 608,
                    width: 96,
                    crumbleLeft: true,
                    crumbleRight: true,
                },
                { actor: "LedgeOpening", x: 288, y: 608, width: 32 },
                { actor: "Ledge", x: 320, y: 608, width: 256 },
                { actor: "DirtLight", x: 192, y: 640, width: 384, height: 64 },
                { actor: "DirtMedium", x: 128, y: 704, width: 384, height: 128 },
                { actor: "Grass", x: 384, y: 704, width: 128, height: 128 },
                { actor: "DirtLight", x: 512, y: 704, width: 64, height: 128 },
                { actor: "PlantSmall", x: 128, y: 736, width: 256 },
                {
                    actor: "BugCatcher",
                    x: 160,
                    y: 768,
                    direction: 2,
                    roaming: true,
                    roamingDirections: [0, 8],
                    name: "ShopAdvertiser",
                    dialog: [
                        "Hi! I work at a %%%%%%%POKEMON%%%%%%% MART.",
                        "It's a convenient shop, so please visit us in VIRIDIAN CITY.",
                        "I know, I'll give you a sample! Here you go!",
                    ],
                    dialogNext:
                        "We also carry %%%%%%%POKE%%%%%%% BALLs for catching %%%%%%%POKEMON%%%%%%%!",
                    gift: "Potion",
                },
                { actor: "Ledge", x: 512, y: 736, width: 64, jagged: true },
                {
                    macro: "Checkered",
                    actors: ["", "Flower"],
                    x: 256,
                    y: 784,
                    xnum: 8,
                    ynum: 2,
                    xwidth: 16,
                    yheight: 16,
                },
                { actor: "DirtLight", x: 128, y: 832, width: 448, height: 64 },
                {
                    actor: "Sign",
                    x: 288,
                    y: 864,
                    dialog: "ROUTE 1 \n PALLET TOWN - VIRIDIAN CITY",
                },
                { actor: "Ledge", x: 128, y: 864, width: 64, jagged: true },
                { actor: "Ledge", x: 320, y: 864, width: 256, jagged: true },
                { actor: "PlantSmall", x: 96, y: 896, height: 256 },
                { actor: "DirtMedium", x: 128, y: 896, width: 192, height: 288 },
                { actor: "Grass", x: 192, y: 896, width: 128, height: 64 },
                { actor: "DirtLight", x: 320, y: 896, width: 64, height: 160 },
                { actor: "DirtMedium", x: 384, y: 896, width: 192, height: 288 },
                { actor: "Grass", x: 448, y: 896, width: 128, height: 64 },
                { actor: "PlantSmall", x: 576, y: 896, height: 256 },
                { actor: "Grass", x: 128, y: 960, width: 128, height: 64 },
                { actor: "Grass", x: 384, y: 960, width: 128, height: 64 },
                {
                    macro: "Checkered",
                    actors: ["", "Flower"],
                    x: 256,
                    y: 976,
                    xnum: 4,
                    ynum: 2,
                    xwidth: 16,
                    yheight: 16,
                },
                {
                    macro: "Checkered",
                    actors: ["", "Flower"],
                    x: 512,
                    y: 976,
                    xnum: 4,
                    ynum: 2,
                    xwidth: 16,
                    yheight: 16,
                },
                { actor: "FenceWide", x: 128, y: 1024, width: 192 },
                { actor: "DirtMedium", x: 320, y: 1024, width: 64, height: 160 },
                { actor: "Grass", x: 320, y: 1024, width: 64, height: 160 },
                { actor: "FenceWide", x: 384, y: 1024, width: 192 },
                { actor: "FenceWide", x: 288, y: 1056, height: 128 },
                { actor: "FenceWide", x: 384, y: 1056, height: 128 },
                {
                    actor: "ThemePlayer",
                    x: 320,
                    y: 1120,
                    width: 64,
                    theme: "Viridian City from Pallet Town",
                },
                { actor: "FenceWide", x: 96, y: 1152 },
                { actor: "ThemePlayer", x: 320, y: 1152, width: 64, theme: "Pallet Town" },
                { actor: "FenceWide", x: 576, y: 1152 },
                {
                    actor: "AreaSpawner",
                    y: 1152,
                    width: 640,
                    map: "Pallet Town",
                    area: "Land",
                    direction: 2,
                },
            ],
        },
    },
};
