import { MapRaw } from "../../sections/Maps";

export const Route2: MapRaw = {
    name: "Route 2",
    theme: "Viridian City from Pallet Town",
    locationDefault: "Viridian Forest Top",
    locations: {
        "Viridian Forest Top": {
            area: "Land",
            direction: 0,
        },
        "Viridian Forest Bottom": {
            area: "Land",
            push: true,
        },
    },
    areas: {
        Land: {
            allowCycling: true,
            width: 896,
            height: 2368,
            creation: [
                {
                    actor: "ThemePlayer",
                    x: 384,
                    width: 64,
                    height: 1600,
                    theme: "Viridian City from Pallet Town",
                },
                {
                    actor: "AreaSpawner",
                    width: 896,
                    map: "Pewter City",
                    area: "Land",
                    direction: 1,
                    offsetX: -192,
                },
                { actor: "DirtMedium", width: 384, height: 64 },
                { actor: "PlantSmall", width: 384, height: 64 },
                { actor: "DirtMedium", x: 448, width: 480, height: 64 },
                { actor: "PlantSmall", x: 448, width: 480, height: 64 },
                {
                    macro: "Checkered",
                    actors: ["DirtClean", "DirtWhite"],
                    x: 384,
                    xnum: 2,
                    ynum: 40,
                },
                { actor: "DirtMedium", y: 64, width: 128, height: 2304 },
                { actor: "PlantSmall", y: 64, width: 128, height: 2304 },
                { actor: "DirtMedium", x: 768, y: 64, width: 160, height: 2304 },
                { actor: "PlantSmall", x: 768, y: 64, width: 160, height: 2304 },
                { actor: "DirtMedium", x: 128, y: 64, width: 256, height: 256 },
                { actor: "PlantSmall", x: 128, y: 64, width: 256, height: 64 },
                { actor: "DirtMedium", x: 448, y: 64, width: 320, height: 64 },
                { actor: "PlantSmall", x: 448, y: 64, width: 320, height: 64 },
                { actor: "Grass", x: 128, y: 128, width: 256, height: 192 },
                { actor: "DirtWhite", x: 448, y: 128, width: 64, height: 128 },
                { actor: "FenceVertical", x: 448, y: 128, width: 32, height: 128 },
                { actor: "DirtLight", x: 512, y: 128, width: 256, height: 128 },
                { actor: "DirtWhite", x: 448, y: 256 },
                {
                    macro: "Mountain",
                    x: 448,
                    y: 256,
                    width: 256,
                    height: 128,
                    top: true,
                    right: true,
                    bottom: true,
                    left: true,
                    opening: true,
                },
                { actor: "DirtLight", x: 672, y: 256, width: 96, height: 128 },
                { actor: "DirtLight", x: 128, y: 320, width: 320, height: 64 },
                { actor: "DirtMedium", x: 128, y: 384, width: 320, height: 192 },
                { actor: "PlantSmall", x: 128, y: 384, width: 96 },
                { actor: "PlantSmall", x: 256, y: 384, height: 64 },
                { actor: "Tree", x: 288, y: 384 },
                { actor: "PlantSmall", x: 320, y: 384, width: 128 },
                { actor: "DirtLight", x: 448, y: 384, width: 128, height: 128 },
                { actor: "DirtMedium", x: 576, y: 384, width: 192, height: 64 },
                {
                    macro: "Checkered",
                    actors: ["", "Flower"],
                    x: 576,
                    y: 400,
                    xnum: 8,
                    ynum: 2,
                    xwidth: 16,
                    yheight: 16,
                },
                { actor: "PlantSmall", x: 192, y: 416 },
                { actor: "Sign", x: 480, y: 416 },
                {
                    actor: "HiddenTransporter",
                    x: 224,
                    y: 416,
                    directionRequired: 8,
                    entrance: "Viridian Forest Top",
                    transport: { map: "Viridian Forest", location: "Gate North Door North" },
                },
                { macro: "Building", x: 192, y: 448, door: true },
                { actor: "DirtLight", x: 576, y: 448, width: 192, height: 64 },
                { actor: "DirtMedium", x: 448, y: 512, width: 256, height: 64 },
                { actor: "DirtLight", x: 704, y: 512, width: 64, height: 256 },
                { actor: "FenceWide", x: 128, y: 544, width: 64 },
                { actor: "FenceWide", x: 320, y: 544, width: 256 },
                { actor: "BrickRoad", x: 128, y: 576, width: 256, height: 64 },
                { actor: "DirtMedium", x: 384, y: 576, width: 192, height: 192 },
                { actor: "PlantSmall", x: 384, y: 576, width: 192, height: 192 },
                { actor: "DirtMedium", x: 576, y: 576, width: 128, height: 64 },
                { actor: "DirtLight", x: 128, y: 640, width: 256, height: 64 },
                { actor: "DirtLight", x: 576, y: 640, width: 128, height: 128 },
                { macro: "House", x: 576, y: 640, door: true },
                { actor: "Ledge", x: 128, y: 672, width: 256, jagged: true },
                { actor: "DirtMedium", x: 128, y: 704, width: 64, height: 64 },
                { actor: "Grass", x: 128, y: 704, width: 64, height: 64 },
                {
                    macro: "Checkered",
                    actors: ["DirtClean", "DirtWhite"],
                    x: 192,
                    y: 704,
                    xnum: 2,
                    ynum: 2,
                },
                { actor: "DirtMedium", x: 256, y: 704, width: 128, height: 64 },
                { actor: "Grass", x: 256, y: 704, width: 128, height: 64 },
                { actor: "DirtMedium", x: 128, y: 768, width: 640, height: 704 },
                { actor: "PlantSmall", x: 128, y: 768, width: 448, height: 512 },
                { actor: "PlantSmall", x: 576, y: 768, height: 64 },
                { actor: "Tree", x: 608, y: 768 },
                { actor: "PlantSmall", x: 640, y: 768, width: 128 },
                { actor: "Ledge", x: 576, y: 928, width: 96, crumbleRight: true },
                { actor: "LedgeOpening", x: 672, y: 928 },
                { actor: "Ledge", x: 704, y: 928, width: 64 },
                {
                    macro: "Checkered",
                    actors: ["", "Flower"],
                    x: 704,
                    y: 976,
                    xnum: 4,
                    ynum: 2,
                    xwidth: 16,
                    yheight: 16,
                },
                { actor: "Ledge", x: 576, y: 1056, width: 96, crumbleRight: true },
                { actor: "LedgeOpening", x: 672, y: 1056 },
                { actor: "Ledge", x: 704, y: 1056, width: 64 },
                {
                    macro: "Checkered",
                    actors: ["", "Flower"],
                    x: 704,
                    y: 1104,
                    xnum: 4,
                    ynum: 2,
                    xwidth: 16,
                    yheight: 16,
                },
                { actor: "FenceWide", x: 576, y: 1184, width: 64 },
                { actor: "FenceWide", x: 704, y: 1184, width: 64 },
                { macro: "Building", x: 576, y: 1216, width: 192, door: true },
                { actor: "PlantSmall", x: 128, y: 1280, width: 96 },
                { actor: "PlantSmall", x: 256, y: 1280 },
                { actor: "Tree", x: 288, y: 1280 },
                { actor: "PlantSmall", x: 320, y: 1280, width: 256 },
                { actor: "PlantSmall", x: 192, y: 1312 },
                { actor: "PlantSmall", x: 256, y: 1312 },
                { actor: "PlantSmall", x: 448, y: 1312, width: 128, height: 160 },
                {
                    macro: "Building",
                    x: 192,
                    y: 1344,
                    width: 128,
                    height: 128,
                    door: true,
                    entrance: "Viridian Forest Bottom",
                    transport: { map: "Viridian Forest", location: "Gate South Door South" },
                },
                { actor: "FenceWide", x: 128, y: 1440, width: 64 },
                { actor: "FenceWide", x: 320, y: 1440, width: 128 },
                { actor: "Ledge", x: 576, y: 1440, crumbleRight: true },
                { actor: "LedgeOpening", x: 608, y: 1440 },
                { actor: "Ledge", x: 640, y: 1440, width: 128 },
                { actor: "BrickRoad", x: 128, y: 1472, width: 320, height: 64 },
                { actor: "DirtMedium", x: 448, y: 1472, width: 320, height: 800 },
                { actor: "PlantSmall", x: 480, y: 1472, height: 256 },
                { actor: "Pokeball", x: 544, y: 1504 },
                { actor: "DirtLight", x: 128, y: 1536, width: 256, height: 64 },
                {
                    macro: "Checkered",
                    actors: ["DirtClean", "DirtWhite"],
                    x: 384,
                    y: 1536,
                    xnum: 2,
                    ynum: 2,
                },
                {
                    macro: "Checkered",
                    actors: ["", "Flower"],
                    x: 640,
                    y: 1552,
                    xnum: 8,
                    ynum: 2,
                    xwidth: 16,
                    yheight: 16,
                },
                { actor: "Ledge", x: 128, y: 1568, width: 256, jagged: true },
                { actor: "DirtMedium", x: 128, y: 1600, width: 64, height: 768 },
                {
                    macro: "Checkered",
                    actors: ["DirtClean", "DirtWhite"],
                    x: 192,
                    y: 1600,
                    xnum: 2,
                    ynum: 48,
                },
                { actor: "DirtMedium", x: 256, y: 1600, width: 192, height: 320 },
                { actor: "Grass", x: 256, y: 1600, width: 192, height: 128 },
                {
                    macro: "Checkered",
                    actors: ["", "Flower"],
                    x: 128,
                    y: 1616,
                    xnum: 4,
                    ynum: 2,
                    xwidth: 16,
                    yheight: 16,
                },
                { actor: "Ledge", x: 512, y: 1632, width: 96, crumbleRight: true },
                { actor: "LedgeOpening", x: 608, y: 1632 },
                { actor: "Ledge", x: 640, y: 1632, width: 128 },
                {
                    macro: "Checkered",
                    actors: ["", "Flower"],
                    x: 128,
                    y: 1680,
                    xnum: 4,
                    ynum: 2,
                    xwidth: 16,
                    yheight: 16,
                },
                { actor: "Tree", x: 512, y: 1728 },
                {
                    macro: "Checkered",
                    actors: ["", "Flower"],
                    x: 128,
                    y: 1744,
                    xnum: 4,
                    ynum: 2,
                    xwidth: 16,
                    yheight: 16,
                },
                { actor: "PlantSmall", x: 320, y: 1760, width: 256 },
                { actor: "PlantSmall", x: 288, y: 1792, width: 256, height: 64 },
                {
                    macro: "Checkered",
                    actors: ["", "Flower"],
                    x: 128,
                    y: 1808,
                    xnum: 4,
                    ynum: 2,
                    xwidth: 16,
                    yheight: 16,
                },
                { actor: "Pokeball", x: 544, y: 1792 },
                { actor: "PlantSmall", x: 320, y: 1856, width: 224 },
                {
                    macro: "Checkered",
                    actors: ["", "Flower"],
                    x: 128,
                    y: 1872,
                    xnum: 4,
                    ynum: 2,
                    xwidth: 16,
                    yheight: 16,
                },
                {
                    macro: "Checkered",
                    actors: ["", "Flower"],
                    x: 576,
                    y: 1872,
                    xnum: 4,
                    ynum: 2,
                    xwidth: 16,
                    yheight: 16,
                },
                { actor: "PlantSmall", x: 512, y: 1888, height: 96 },
                { actor: "DirtLight", x: 256, y: 1920, width: 192, height: 64 },
                {
                    macro: "Checkered",
                    actors: ["", "Flower"],
                    x: 128,
                    y: 1936,
                    xnum: 4,
                    ynum: 2,
                    xwidth: 16,
                    yheight: 16,
                },
                {
                    macro: "Checkered",
                    actors: ["", "Flower"],
                    x: 576,
                    y: 1936,
                    xnum: 8,
                    ynum: 2,
                    xwidth: 16,
                    yheight: 16,
                },
                { actor: "PlantSmall", x: 128, y: 1984, width: 64, height: 384 },
                { actor: "DirtMedium", x: 192, y: 1984, width: 192, height: 128 },
                { actor: "DirtLight", x: 384, y: 1984, width: 64, height: 256 },
                { actor: "Tree", x: 512, y: 1984 },
                { actor: "PlantSmall", x: 512, y: 2016, width: 64 },
                { actor: "Ledge", x: 192, y: 2016, width: 160, crumbleRight: true },
                { actor: "LedgeOpening", x: 352, y: 2016 },
                { actor: "Ledge", x: 384, y: 2016, width: 128, crumbleLeft: true },
                { actor: "Ledge", x: 576, y: 2016, crumbleRight: true },
                { actor: "LedgeOpening", x: 608, y: 2016 },
                { actor: "Ledge", x: 640, y: 2016, width: 128 },
                { actor: "PlantSmall", x: 512, y: 2048, height: 192 },
                {
                    macro: "Checkered",
                    actors: ["", "Flower"],
                    x: 192,
                    y: 2064,
                    xnum: 8,
                    ynum: 2,
                    xwidth: 16,
                    yheight: 16,
                },
                { actor: "DirtLight", x: 192, y: 2112, width: 192, height: 64 },
                {
                    macro: "Checkered",
                    actors: ["", "Flower"],
                    x: 576,
                    y: 2128,
                    xnum: 8,
                    ynum: 2,
                    xwidth: 16,
                    yheight: 16,
                },
                { actor: "Sign", x: 288, y: 2144 },
                {
                    macro: "Checkered",
                    actors: ["DirtClean", "DirtWhite"],
                    x: 192,
                    y: 2176,
                    xnum: 2,
                    ynum: 4,
                },
                { actor: "DirtMedium", x: 256, y: 2176, width: 128, height: 64 },
                {
                    macro: "Checkered",
                    actors: ["", "Flower"],
                    x: 256,
                    y: 2192,
                    xnum: 8,
                    ynum: 2,
                    xwidth: 16,
                    yheight: 16,
                },
                {
                    macro: "Checkered",
                    actors: ["", "Flower"],
                    x: 576,
                    y: 2192,
                    xnum: 8,
                    ynum: 2,
                    xwidth: 16,
                    yheight: 16,
                },
                {
                    macro: "Checkered",
                    actors: ["DirtClean", "DirtWhite"],
                    x: 256,
                    y: 2240,
                    xnum: 6,
                    ynum: 2,
                },
                { actor: "Tree", x: 512, y: 2240 },
                { actor: "DirtMedium", x: 448, y: 2272, width: 320, height: 96 },
                { actor: "PlantSmall", x: 448, y: 2272, width: 320, height: 96 },
                { actor: "DirtMedium", x: 192, y: 2304, width: 128, height: 64 },
                { actor: "PlantSmall", x: 192, y: 2304, width: 128, height: 64 },
                { actor: "DirtWhite", x: 320, y: 2304, width: 64, height: 64 },
                { actor: "FenceVertical", x: 320, y: 2304, width: 32, height: 64 },
                {
                    actor: "ThemePlayer",
                    x: 352,
                    y: 2304,
                    width: 96,
                    theme: "Viridian City from Pallet Town",
                },
                {
                    macro: "Checkered",
                    actors: ["DirtClean", "DirtWhite"],
                    x: 384,
                    y: 2304,
                    xnum: 2,
                    ynum: 2,
                },
                {
                    actor: "AreaSpawner",
                    y: 2336,
                    width: 2432,
                    map: "Viridian City",
                    area: "Land",
                    direction: 1,
                    offsetX: -192,
                },
            ],
        },
    },
};
