import { MapRaw } from "../../sections/Maps";

export const ViridianForest: MapRaw = {
    name: "Viridian Forest",
    theme: "Viridian Forest",
    locationDefault: "Forest Top",
    locations: {
        "Gate North Door North": {
            area: "Gate North",
            direction: 2,
            push: true,
        },
        "Gate North Door South": {
            area: "Gate North",
            direction: 0,
        },
        "Forest Bottom": {
            area: "Forest",
            xloc: 544,
            yloc: 1504,
            direction: 0,
        },
        "Forest Top": {
            area: "Forest",
            xloc: 32,
            direction: 2,
        },
        "Gate South Door North": {
            area: "Gate South",
            direction: 2,
            push: true,
        },
        "Gate South Door South": {
            area: "Gate South",
            direction: 0,
        },
    },
    areas: {
        "Gate North": {
            allowCycling: false,
            width: 320,
            height: 256,
            theme: "Pewter City",
            invisibleWallBorders: true,
            creation: [
                { actor: "WallIndoorFancyWithDarkBottom", width: 160 },
                { actor: "InvisibleWall", width: 160 },
                {
                    actor: "Door",
                    x: 160,
                    indoor: true,
                    transport: { map: "Route 2", location: "Viridian Forest Top" },
                    entrance: "Gate North Door North",
                },
                { actor: "WallIndoorFancyWithDarkBottom", x: 192, width: 128 },
                { actor: "InvisibleWall", x: 192, width: 128 },
                { actor: "FloorCheckered", y: 32, width: 320, height: 224 },
                { actor: "PottedPalmTree", y: 64, height: 192 },
                {
                    actor: "Guy",
                    x: 96,
                    y: 64,
                    roaming: true,
                    roamingDirections: [],
                    dialog: [
                        "Many %%%%%%%POKEMON%%%%%%% live only in forests and caves.",
                        "You need to look everywhere to get different kinds!",
                    ],
                },
                { actor: "Table1x2", x: 192, y: 64 },
                { actor: "Table1x2", x: 256, y: 64 },
                { actor: "PottedPalmTree", x: 288, y: 64, height: 192 },
                {
                    actor: "OldMan",
                    x: 64,
                    y: 160,
                    roaming: true,
                    roamingDirections: [],
                    dialog: [
                        "Have you noticed the bushes on the roadside?",
                        "They can be cut down by a special %%%%%%%POKEMON%%%%%%% move.",
                    ],
                },
                { actor: "Table1x2", x: 192, y: 160 },
                { actor: "Table1x2", x: 256, y: 160 },
                {
                    actor: "Doormat",
                    x: 128,
                    y: 224,
                    width: 64,
                    entrance: "Gate North Door South",
                },
                {
                    actor: "HiddenTransporter",
                    x: 128,
                    y: 224,
                    width: 64,
                    directionRequired: 2,
                    transport: { map: "Viridian Forest", location: "Forest Top" },
                },
            ],
        },
        Forest: {
            allowCycling: true,
            width: 1088,
            height: 1536,
            wildPokemon: {
                grass: [
                    {
                        title: "CATERPIE".split(""),
                        levels: [3, 5],
                        rate: 0.5,
                    },
                    {
                        title: "METAPOD".split(""),
                        levels: [4, 5, 6],
                        rate: 0.35,
                    },
                    {
                        title: "WEEDLE".split(""),
                        level: 3,
                        rate: 0.05,
                    },
                    {
                        title: "KAKUNA".split(""),
                        level: 4,
                        rate: 0.05,
                    },
                    {
                        title: "PIKACHU".split(""),
                        levels: [3, 5],
                        rate: 0.05,
                    },
                ],
            },
            creation: [
                {
                    actor: "HiddenTransporter",
                    x: 32,
                    width: 64,
                    directionRequired: 0,
                    transport: "Gate North Door South",
                },
                { actor: "DirtForest", width: 1088, height: 1536 },
                { actor: "Stump", height: 832 },
                { actor: "Stump", x: 96, height: 704 },
                { actor: "PlantLarge", x: 128, height: 704 },
                { actor: "Stump", x: 192, width: 256 },
                { actor: "PlantLarge", x: 448, height: 512 },
                { actor: "Stump", x: 512, width: 576 },
                {
                    actor: "Sign",
                    x: 64,
                    y: 32,
                    forest: true,
                    dialog: "LEAVING \n VIRIDIAN FOREST PEWTER CITY AHEAD",
                },
                { actor: "Stump", x: 1056, y: 32, height: 1056 },
                { actor: "Stump", x: 640, y: 96, width: 320 },
                { actor: "ForestDirt", x: 416, y: 112 },
                { actor: "ForestDirt", x: 608, y: 112 },
                { actor: "ForestDirt", x: 992, y: 112 },
                { actor: "Stump", x: 288, y: 128, height: 640 },
                { actor: "Stump", x: 320, y: 128, height: 512 },
                { actor: "Stump", x: 608, y: 128, height: 128 },
                { actor: "PlantLarge", x: 640, y: 128, width: 320, height: 128 },
                { actor: "Stump", x: 960, y: 128, height: 128 },
                { actor: "Grass", x: 32, y: 192, width: 64, height: 576 },
                { actor: "Grass", x: 192, y: 192, width: 96, height: 576 },
                { actor: "Grass", x: 352, y: 192, width: 96, height: 384 },
                { actor: "Grass", x: 512, y: 192, width: 96, height: 384 },
                { actor: "Grass", x: 608, y: 256, width: 160, height: 64 },
                { actor: "ForestDirt", x: 864, y: 304 },
                { actor: "Stump", x: 608, y: 320, height: 320 },
                { actor: "PlantLarge", x: 640, y: 320, width: 128, height: 320 },
                { actor: "Stump", x: 768, y: 320, height: 960 },
                { actor: "Stump", x: 864, y: 320, height: 256 },
                { actor: "PlantLarge", x: 896, y: 320, height: 256 },
                { actor: "Grass", x: 960, y: 320, width: 96, height: 256 },
                { actor: "Pokeball", x: 800, y: 352, name: "Item One", item: "Antidote" },
                {
                    actor: "Sign",
                    x: 832,
                    y: 544,
                    forest: true,
                    dialog: [
                        "TRAINER TIPS",
                        "Contact PROF. OAK via PC to get your %%%%%%%POKEDEX%%%%%%% evaluated!",
                    ],
                },
                {
                    actor: "BugCatcher",
                    x: 960,
                    y: 608,
                    name: "Trainer Two",
                    direction: 3,
                    sight: 16,
                    trainer: true,
                    reward: 280,
                    dialog: "Yo! You can't jam out if you're a %%%%%%%POKEMON%%%%%%% trainer!",
                    textDefeat: "BUG CATCHER: No! CATERPIE can't cut it!",
                    dialogNext: "Ssh! You'll scare the bugs away!",
                    actors: [
                        {
                            title: ["W", "E", "E", "D", "L", "E"],
                            level: 28,
                        },
                        {
                            title: ["K", "A", "K", "U", "N", "A"],
                            level: 28,
                        },
                        {
                            title: ["W", "E", "E", "D", "L", "E"],
                            level: 28,
                        },
                    ],
                },
                { actor: "ForestDirt", x: 416, y: 624 },
                { actor: "ForestDirt", x: 864, y: 624 },
                { actor: "PlantLarge", x: 320, y: 640, width: 448, height: 128 },
                { actor: "Grass", x: 800, y: 640, width: 96, height: 384 },
                { actor: "PlantLarge", x: 896, y: 640, height: 384 },
                { actor: "Stump", x: 960, y: 640, height: 384 },
                { actor: "Grass", x: 96, y: 704, height: 64 },
                {
                    actor: "BugCatcher",
                    x: 64,
                    y: 576,
                    name: "Trainer Three",
                    direction: 3,
                    sight: 4,
                    reward: 360,
                    dialog: "Hey, wait up! What's the hurry?",
                    textDefeat: "BUG CATCHER:  give! You're good at this!",
                    dialogNext: [
                        "Sometimes, you can find stuff on the ground!",
                        "I'm looking for the stuff I dropped!",
                    ],
                    actors: [
                        {
                            title: "Weedle",
                            level: 36,
                        },
                    ],
                },
                {
                    actor: "Sign",
                    x: 128,
                    y: 768,
                    forest: true,
                    dialog: [
                        "TRAINER TIPS",
                        "No stealing of %%%%%%%POKEMON%%%%%%% from other trainers! Catch only wild %%%%%%%POKEMON%%%%%%%!",
                    ],
                },
                { actor: "ForestDirt", x: 224, y: 816 },
                { actor: "Stump", x: 416, y: 768, height: 192 },
                { actor: "PlantLarge", x: 448, y: 768, width: 320, height: 192 },
                { actor: "PlantLarge", y: 832, width: 320, height: 128 },
                { actor: "Stump", x: 320, y: 832, height: 128 },
                { actor: "Pokeball", x: 384, y: 896, name: "Item Two", item: "Potion" },
                { actor: "Stump", y: 960, height: 64 },
                { actor: "Grass", x: 32, y: 960, width: 256, height: 64 },
                { actor: "Stump", x: 288, y: 960, height: 64 },
                { actor: "PlantLarge", x: 320, y: 960, width: 448 },
                { actor: "PlantLarge", y: 1024, width: 192, height: 256 },
                { actor: "Grass", x: 256, y: 1024, width: 256, height: 64 },
                { actor: "Sign", x: 512, y: 1024, forest: true },
                { actor: "Grass", x: 576, y: 1024, height: 320 },
                { actor: "Stump", x: 608, y: 1024, height: 256 },
                { actor: "PlantLarge", x: 640, y: 1024, width: 128, height: 256 },
                { actor: "Grass", x: 800, y: 1024, height: 320 },
                {
                    actor: "BugCatcher",
                    x: 928,
                    y: 1056,
                    name: "Trainer One",
                    direction: 3,
                    sight: 12,
                    trainer: true,
                    reward: 240,
                    dialog: "Hey! You have %%%%%%%POKEMON%%%%%%%! Come on! Let's battle' em!",
                    textDefeat: "BUG CATCHER: No! CATERPIE can't cut it!",
                    dialogNext: "Ssh! You'll scare the bugs away!",
                    actors: [
                        {
                            title: ["W", "E", "E", "D", "L", "E"],
                            level: 24,
                        },
                        {
                            title: ["C", "A", "T", "E", "R", "P", "I", "E"],
                            level: 24,
                        },
                    ],
                },
                { actor: "ForestDirt", x: 224, y: 1072 },
                { actor: "ForestDirt", x: 992, y: 1072 },
                { actor: "Grass", x: 256, y: 1088, height: 256 },
                { actor: "Stump", x: 288, y: 1088, height: 192 },
                { actor: "PlantLarge", x: 320, y: 1088, width: 128, height: 192 },
                { actor: "Stump", x: 448, y: 1088, height: 192 },
                { actor: "Grass", x: 480, y: 1088, height: 256 },
                { actor: "PlantLarge", x: 896, y: 1088, width: 192, height: 192 },
                { actor: "Stump", y: 1280, height: 128 },
                { actor: "Grass", x: 32, y: 1280, width: 128, height: 128 },
                { actor: "Grass", x: 288, y: 1280, width: 192, height: 64 },
                { actor: "Grass", x: 608, y: 1280, width: 192, height: 64 },
                {
                    actor: "Sign",
                    x: 768,
                    y: 1280,
                    forest: true,
                    dialog: [
                        "TRAINER TIPS",
                        "If you want to avoid battles",
                        "stay away from grassy areas!",
                    ],
                },
                {
                    actor: "BugCatcher",
                    x: 864,
                    y: 1280,
                    roaming: true,
                    roamingDirections: [],
                    dialog: [
                        "I ran out of %%%%%%%POKE%%%%%%% BALLs to catch %%%%%%%POKEMON%%%%%%% with!",
                        "You should carry extras!",
                    ],
                },
                { actor: "Grass", x: 896, y: 1280, width: 160, height: 128 },
                { actor: "Stump", x: 1056, y: 1280, height: 128 },
                { actor: "PlantLarge", x: 512, y: 1312 },
                { actor: "PlantLarge", y: 1408, width: 448, height: 128 },
                { actor: "Stump", x: 448, y: 1408, height: 128 },
                { actor: "Stump", x: 608, y: 1408, height: 128 },
                { actor: "PlantLarge", x: 640, y: 1408, width: 448, height: 128 },
                {
                    actor: "BugCatcher",
                    x: 640,
                    y: 1472,
                    direction: 2,
                    directionPreferred: 2,
                    dialog: [
                        "I cam here with some friends!",
                        "They're out for %%%%%%%POKEMON%%%%%%% fights!",
                    ],
                },
                {
                    actor: "Sign",
                    x: 576,
                    y: 1440,
                    forest: true,
                    dialog: [
                        "TRAINER TIPS",
                        "Weaken %%%%%%%POKEMON%%%%%%% before attempting capture!",
                        "When healthy, they may escape!",
                    ],
                },
                { actor: "GroundArrow", x: 528, y: 1472, width: 32 },
                {
                    actor: "HiddenTransporter",
                    x: 480,
                    y: 1504,
                    width: 128,
                    directionRequired: 2,
                    transport: "Gate South Door North",
                },
            ],
        },
        "Gate South": {
            allowCycling: false,
            width: 320,
            height: 256,
            theme: "Pewter City",
            invisibleWallBorders: true,
            creation: [
                { actor: "WallIndoorFancyWithDarkBottom", width: 160 },
                { actor: "InvisibleWall", width: 160 },
                {
                    actor: "Door",
                    x: 160,
                    indoor: true,
                    transport: "Forest Bottom",
                    entrance: "Gate South Door North",
                },
                { actor: "WallIndoorFancyWithDarkBottom", x: 192, width: 128 },
                { actor: "InvisibleWall", x: 192, width: 128 },
                { actor: "FloorCheckered", y: 32, width: 320, height: 224 },
                { actor: "PottedPalmTree", y: 64, height: 192 },
                { actor: "Table1x2", x: 192, y: 64 },
                { actor: "Table1x2", x: 256, y: 64 },
                { actor: "PottedPalmTree", x: 288, y: 64, height: 192 },
                { actor: "Table1x2", x: 192, y: 160 },
                { actor: "Table1x2", x: 256, y: 160 },
                {
                    actor: "Lady",
                    x: 256,
                    y: 128,
                    direction: 3,
                    dialog: "Are you going to VIRIDIAN FOREST? Be careful, it's a natural maze!",
                },
                {
                    actor: "LittleGirl",
                    x: 64,
                    y: 160,
                    direction: 0,
                    roaming: true,
                    roamingDirections: [0, 2],
                    dialog: "RATTATA may be small, but its bite is wicked! Did you get one?",
                },
                {
                    actor: "Doormat",
                    x: 128,
                    y: 224,
                    width: 64,
                    entrance: "Gate South Door South",
                },
                {
                    actor: "HiddenTransporter",
                    x: 128,
                    y: 224,
                    width: 64,
                    directionRequired: 2,
                    transport: { map: "Route 2", location: "Viridian Forest Bottom" },
                },
            ],
        },
    },
};
