FullScreenPokemon.prototype.settings.audio = {
    "directory": "Sounds",
    "fileTypes": ["mp3"],
    "statistics": {
        "prefix": "FullScreenPokemon::AudioPlayer::",
        "values": {
            "volume": {
                "valueDefault": 0.5,
                "storeLocally": true
            },
            "muted": {
                "valueDefault": 0,
                "storeLocally": true
            }
        }
    },
    "library": {
        "Themes": [
            "Battle (VS Trainer)",
            "Battle (VS Wild Pokemon)",
            "Battle VS Gym Leader",
            "Casino",
            "Celadon City",
            "Cerulean City's Theme",
            "Cinnabar Islands Theme",
            "Codename St Anne",
            "Cycling",
            "Ending",
            "Evolution",
            "Guidepost",
            "Into The Palace",
            "Jigglypuff's Song",
            "Last Battle VS Rival",
            "Lavender Town's Theme",
            "Mt Moon Cave",
            "Oak Research Lab",
            "Ocean",
            "Opening",
            "Pallet Town",
            "Pewter City",
            "Pokemon Center",
            "Pokemon Gym",
            "Pokemon Mansion",
            "Pokemon Recovery",
            "Pokemon Tower",
            "Pokemon Whistle",
            "Professor Oak",
            "Rival Appears",
            "Sylph Company",
            "Team Rocket Hideout",
            "The Final Road",
            "The Road To Cerulean From Mt Moon",
            "The Road To Lavender Town From Vermillion",
            "The Road To Viridian City From Palette",
            "To Bill's Origin From Cerulean",
            "Trainer Appears (Girl Chapter)",
            "Trainer Appears Bad Guy Chapter",
            "Trainer Appears Boy Chapter",
            "Vermillion City's Theme",
            "Victory (VS Trainer)",
            "Victory (VS Wild Pokemon)",
            "Victory VS Gym Leader",
            "Viridian Forest"
        ],
        "Sounds": [
            "Abra",
            "Aerodactyl",
            "Alakazam",
            "Arbok",
            "Arcanine",
            "Articuno",
            "Beedrill",
            "Bellsprout",
            "Blastoise",
            "Bulbasaur",
            "Butterfree",
            "Caterpie",
            "Chansey",
            "Charizard",
            "Charmander",
            "Charmeleon",
            "Clefable",
            "Clefairy",
            "Cloyster",
            "Cubone",
            "Dewgong",
            "Diglett",
            "Ditto",
            "Dodrio",
            "Doduo",
            "Dragonair",
            "Dragonite",
            "Dratini",
            "Drowzee",
            "Dugtrio",
            "Eevee",
            "Ekans",
            "Electabuzz",
            "Electrode",
            "Exeggcute",
            "Exeggutor",
            "Farfetch D",
            "Fearow",
            "Flareon",
            "Gengar",
            "Geodude",
            "Ghastly",
            "Gloom",
            "Golbat",
            "Goldeen",
            "Golduck",
            "Golem",
            "Graveler",
            "Grimer",
            "Growlithe",
            "Gyarados",
            "Haunter",
            "Hitmonchan",
            "Hitmonlee",
            "Horsea",
            "Hypno",
            "Ivysaur",
            "Jigglypuff",
            "Jolteon",
            "Jynx",
            "Kabuto",
            "Kabutops",
            "Kadabra",
            "Kakuna",
            "Kangaskhan",
            "Kingler",
            "Koffing",
            "Krabby",
            "Lapras",
            "Lickitung",
            "Machamp",
            "Machoke",
            "Machop",
            "Magikarp",
            "Magmar",
            "Magnemite",
            "Magneton",
            "Mankey",
            "Marowak",
            "Metapod",
            "Mew",
            "Mewto",
            "Moltres",
            "Mr Mime",
            "Muk",
            "Nidoking",
            "Nidoqueen",
            "Nidoran",
            "Nidorina",
            "Nidorino",
            "Ninetails",
            "Nyaasu",
            "Oddish",
            "Omanyte",
            "Omastar",
            "Onix",
            "Paras",
            "Parasect",
            "Persian",
            "Pidgeot",
            "Pidgeotto",
            "Pidgey",
            "Pikachu",
            "Pinsir",
            "Poliwag",
            "Poliwhirl",
            "Poliwrath",
            "Ponyta",
            "Porygon",
            "Primeape",
            "Psyduck",
            "Raichu",
            "Rapidash",
            "Raticate",
            "Rattata",
            "Rhydon",
            "Rhyhorn",
            "Sandshrew",
            "Sandslash",
            "Scyther",
            "Sea King",
            "Seadra",
            "Seel",
            "Shellder",
            "Slowbro",
            "Slowpoke",
            "Snorlax",
            "Spearow",
            "Squirtle",
            "Starmie",
            "Staryu",
            "Tangela",
            "Tauros",
            "Tentacool",
            "Tentacruel",
            "Vaporeaon",
            "Venomoth",
            "Venonat",
            "Venusaur",
            "Victreebell",
            "Vileplume",
            "Voltorb",
            "Vulpix",
            "Wartortle",
            "Weedle",
            "Weepinbell",
            "Weezing",
            "Wigglypuff",
            "Zapdos",
            "Zubat"
        ],
    }
}