FullScreenPokemon.FullScreenPokemon.settings.maps.library["Route 2"] = {
    "name": "Route 2",
    "theme": "Viridian City from Pallet Town",
    "locationDefault": "Viridian Forest Top",
    "locations": {
        "Viridian Forest Top": {
            "area": "Land",
            "direction": 0
        },
        "Viridian Forest Bottom": {
            "area": "Land"
        }
    },
    "areas": {
        "Land": {
            "width": 224,
            "height": 592,
            "creation": [
                { "thing": "ThemePlayer", "x": 96, "width": 16, "height": 400, "theme": "Viridian City from Pallet Town" },
                { "thing": "AreaSpawner", "width": 224, "direction": 0, "map": "Pewter City", "area": "Land", "direction": 1, "offsetX": -48 },
                { "thing": "DirtMedium", "width": 96, "height": 16 },
                { "thing": "PlantSmall", "width": 96, "height": 16 },
                { "thing": "DirtMedium", "x": 112, "width": 120, "height": 16 },
                { "thing": "PlantSmall", "x": 112, "width": 120, "height": 16 },
                { "macro": "Checkered", "things": ["DirtClean", "DirtWhite"], "x": 96, "xnum": 2, "ynum": 10 },
                { "thing": "DirtMedium", "y": 16, "width": 32, "height": 576 },
                { "thing": "PlantSmall", "y": 16, "width": 32, "height": 576 },
                { "thing": "DirtMedium", "x": 192, "y": 16, "width": 40, "height": 576 },
                { "thing": "PlantSmall", "x": 192, "y": 16, "width": 40, "height": 576 },
                { "thing": "DirtMedium", "x": 32, "y": 16, "width": 64, "height": 64 },
                { "thing": "PlantSmall", "x": 32, "y": 16, "width": 64, "height": 16 },
                { "thing": "DirtMedium", "x": 112, "y": 16, "width": 80, "height": 16 },
                { "thing": "PlantSmall", "x": 112, "y": 16, "width": 80, "height": 16 },
                { "thing": "Grass", "x": 32, "y": 32, "width": 64, "height": 48 },
                { "thing": "DirtWhite", "x": 112, "y": 32, "width": 16, "height": 32 },
                { "thing": "FenceVertical", "x": 112, "y": 32, "width": 8, "height": 32 },
                { "thing": "DirtLight", "x": 128, "y": 32, "width": 64, "height": 32 },
                { "thing": "DirtWhite", "x": 112, "y": 64 },
                { "macro": "Mountain", "x": 112, "y": 64, "width": 64, "height": 32, "top": true, "right": true, "bottom": true, "left": true, "opening": true },
                { "thing": "DirtLight", "x": 168, "y": 64, "width": 24, "height": 32 },
                { "thing": "DirtLight", "x": 32, "y": 80, "width": 80, "height": 16 },
                { "thing": "DirtMedium", "x": 32, "y": 96, "width": 80, "height": 48 },
                { "thing": "PlantSmall", "x": 32, "y": 96, "width": 24 },
                { "thing": "PlantSmall", "x": 64, "y": 96, "height": 16 },
                { "thing": "Tree", "x": 72, "y": 96 },
                { "thing": "PlantSmall", "x": 80, "y": 96, "width": 32 },
                { "thing": "DirtLight", "x": 112, "y": 96, "width": 32, "height": 32 },
                { "thing": "DirtMedium", "x": 144, "y": 96, "width": 48, "height": 16 },
                { "macro": "Checkered", "things": ["", "Flower"], "x": 144, "y": 100, "xnum": 8, "ynum": 2, "xwidth": 4, "yheight": 4 },
                { "thing": "PlantSmall", "x": 48, "y": 104 },
                { "thing": "Sign", "x": 120, "y": 104 },
                { "thing": "HiddenTransporter", "x": 56, "y": 104, "directionRequired": 2, "entrance": "Viridian Forest Top", "transport": { "map": "Viridian Forest", "location": "Gate North Door North" } },
                { "macro": "Building", "x": 48, "y": 112, "door": true },
                { "thing": "DirtLight", "x": 144, "y": 112, "width": 48, "height": 16 },
                { "thing": "DirtMedium", "x": 112, "y": 128, "width": 64, "height": 16 },
                { "thing": "DirtLight", "x": 176, "y": 128, "width": 16, "height": 64 },
                { "thing": "FenceWide", "x": 32, "y": 136, "width": 16 },
                { "thing": "FenceWide", "x": 80, "y": 136, "width": 64 },
                { "thing": "BrickRoad", "x": 32, "y": 144, "width": 64, "height": 16 },
                { "thing": "DirtMedium", "x": 96, "y": 144, "width": 48, "height": 48 },
                { "thing": "PlantSmall", "x": 96, "y": 144, "width": 48, "height": 48 },
                { "thing": "DirtMedium", "x": 144, "y": 144, "width": 32, "height": 16 },
                { "thing": "DirtLight", "x": 32, "y": 160, "width": 64, "height": 16 },
                { "thing": "DirtLight", "x": 144, "y": 160, "width": 32, "height": 32 },
                { "macro": "House", "x": 144, "y": 160, "door": true },
                { "thing": "Ledge", "x": 32, "y": 172, "width": 64, "jagged": true },
                { "thing": "DirtMedium", "x": 32, "y": 176, "width": 16, "height": 16 },
                { "thing": "Grass", "x": 32, "y": 176, "width": 16, "height": 16 },
                { "macro": "Checkered", "things": ["DirtClean", "DirtWhite"], "x": 48, "y": 176, "xnum": 2, "ynum": 2 },
                { "thing": "DirtMedium", "x": 64, "y": 176, "width": 32, "height": 16 },
                { "thing": "Grass", "x": 64, "y": 176, "width": 32, "height": 16 },
                { "thing": "DirtMedium", "x": 32, "y": 192, "width": 160, "height": 176 },
                { "thing": "PlantSmall", "x": 32, "y": 192, "width": 112, "height": 128 },
                { "thing": "PlantSmall", "x": 144, "y": 192, "height": 16 },
                { "thing": "Tree", "x": 152, "y": 192 },
                { "thing": "PlantSmall", "x": 160, "y": 192, "width": 32 },
                { "thing": "Ledge", "x": 144, "y": 236, "width": 24, "crumbleRight": true },
                { "thing": "LedgeOpening", "x": 168, "y": 236 },
                { "thing": "Ledge", "x": 176, "y": 236, "width": 16 },
                { "macro": "Checkered", "things": ["", "Flower"], "x": 176, "y": 244, "xnum": 4, "ynum": 2, "xwidth": 4, "yheight": 4 },
                { "thing": "Ledge", "x": 144, "y": 268, "width": 24, "crumbleRight": true },
                { "thing": "LedgeOpening", "x": 168, "y": 268 },
                { "thing": "Ledge", "x": 176, "y": 268, "width": 16 },
                { "macro": "Checkered", "things": ["", "Flower"], "x": 176, "y": 276, "xnum": 4, "ynum": 2, "xwidth": 4, "yheight": 4 },
                { "thing": "FenceWide", "x": 144, "y": 296, "width": 16 },
                { "thing": "FenceWide", "x": 176, "y": 296, "width": 16 },
                { "macro": "Building", "x": 144, "y": 304, "width": 48, "door": true },
                { "thing": "PlantSmall", "x": 32, "y": 320, "width": 24 },
                { "thing": "PlantSmall", "x": 64, "y": 320 },
                { "thing": "Tree", "x": 72, "y": 320 },
                { "thing": "PlantSmall", "x": 80, "y": 320, "width": 64 },
                { "thing": "PlantSmall", "x": 48, "y": 328 },
                { "thing": "PlantSmall", "x": 64, "y": 328 },
                { "thing": "PlantSmall", "x": 112, "y": 328, "width": 32, "height": 40 },
                { "macro": "Building", "x": 48, "y": 336, "width": 32, "height": 32, "door": true, "entrance": "Viridian Forest Bottom", "transport": { "map": "Viridian Forest", "location": "Gate South Door South" } },
                { "thing": "FenceWide", "x": 32, "y": 360, "width": 16 },
                { "thing": "FenceWide", "x": 80, "y": 360, "width": 32 },
                { "thing": "Ledge", "x": 144, "y": 364, "crumbleRight": true },
                { "thing": "LedgeOpening", "x": 152, "y": 364 },
                { "thing": "Ledge", "x": 160, "y": 364, "width": 32 },
                { "thing": "BrickRoad", "x": 32, "y": 368, "width": 80, "height": 16 },
                { "thing": "DirtMedium", "x": 112, "y": 368, "width": 80, "height": 200 },
                { "thing": "PlantSmall", "x": 120, "y": 368, "height": 64 },
                { "thing": "Pokeball", "x": 136, "y": 376 },
                { "thing": "DirtLight", "x": 32, "y": 384, "width": 64, "height": 16 },
                { "macro": "Checkered", "things": ["DirtClean", "DirtWhite"], "x": 96, "y": 384, "xnum": 2, "ynum": 2 },
                { "macro": "Checkered", "things": ["", "Flower"], "x": 160, "y": 388, "xnum": 8, "ynum": 2, "xwidth": 4, "yheight": 4 },
                { "thing": "Ledge", "x": 32, "y": 396, "width": 64, "jagged": true },
                { "thing": "DirtMedium", "x": 32, "y": 400, "width": 16, "height": 192 },
                { "macro": "Checkered", "things": ["DirtClean", "DirtWhite"], "x": 48, "y": 400, "xnum": 2, "ynum": 12 },
                { "thing": "DirtMedium", "x": 64, "y": 400, "width": 48, "height": 80 },
                { "thing": "Grass", "x": 64, "y": 400, "width": 48, "height": 32 },
                { "macro": "Checkered", "things": ["", "Flower"], "x": 32, "y": 404, "xnum": 4, "ynum": 2, "xwidth": 4, "yheight": 4 },
                { "thing": "Ledge", "x": 128, "y": 412, "width": 24, "crumbleRight": true },
                { "thing": "LedgeOpening", "x": 152, "y": 412 },
                { "thing": "Ledge", "x": 160, "y": 412, "width": 32 },
                { "macro": "Checkered", "things": ["", "Flower"], "x": 32, "y": 420, "xnum": 4, "ynum": 2, "xwidth": 4, "yheight": 4 },
                { "thing": "Tree", "x": 128, "y": 432 },
                { "macro": "Checkered", "things": ["", "Flower"], "x": 32, "y": 436, "xnum": 4, "ynum": 2, "xwidth": 4, "yheight": 4 },
                { "thing": "PlantSmall", "x": 80, "y": 440, "width": 64 },
                { "thing": "PlantSmall", "x": 72, "y": 448, "width": 64, "height": 16 },
                { "macro": "Checkered", "things": ["", "Flower"], "x": 32, "y": 452, "xnum": 4, "ynum": 2, "xwidth": 4, "yheight": 4 },
                { "thing": "Pokeball", "x": 136, "y": 448 },
                { "thing": "PlantSmall", "x": 80, "y": 464, "width": 56 },
                { "macro": "Checkered", "things": ["", "Flower"], "x": 32, "y": 468, "xnum": 4, "ynum": 2, "xwidth": 4, "yheight": 4 },
                { "macro": "Checkered", "things": ["", "Flower"], "x": 144, "y": 468, "xnum": 4, "ynum": 2, "xwidth": 4, "yheight": 4 },
                { "thing": "PlantSmall", "x": 128, "y": 472, "height": 24 },
                { "thing": "DirtLight", "x": 64, "y": 480, "width": 48, "height": 16 },
                { "macro": "Checkered", "things": ["", "Flower"], "x": 32, "y": 484, "xnum": 4, "ynum": 2, "xwidth": 4, "yheight": 4 },
                { "macro": "Checkered", "things": ["", "Flower"], "x": 144, "y": 484, "xnum": 8, "ynum": 2, "xwidth": 4, "yheight": 4 },
                { "thing": "PlantSmall", "x": 32, "y": 496, "width": 16, "height": 96 },
                { "thing": "DirtMedium", "x": 48, "y": 496, "width": 48, "height": 32 },
                { "thing": "DirtLight", "x": 96, "y": 496, "width": 16, "height": 64 },
                { "thing": "Tree", "x": 128, "y": 496 },
                { "thing": "PlantSmall", "x": 128, "y": 504, "width": 16 },
                { "thing": "Ledge", "x": 48, "y": 508, "width": 40, "crumbleRight": true },
                { "thing": "LedgeOpening", "x": 88, "y": 508 },
                { "thing": "Ledge", "x": 96, "y": 508, "width": 32, "crumbleLeft": true },
                { "thing": "Ledge", "x": 144, "y": 508, "crumbleRight": true },
                { "thing": "LedgeOpening", "x": 152, "y": 508 },
                { "thing": "Ledge", "x": 160, "y": 508, "width": 32 },
                { "thing": "PlantSmall", "x": 128, "y": 512, "height": 48 },
                { "macro": "Checkered", "things": ["", "Flower"], "x": 48, "y": 516, "xnum": 8, "ynum": 2, "xwidth": 4, "yheight": 4 },
                { "thing": "DirtLight", "x": 48, "y": 528, "width": 48, "height": 16 },
                { "macro": "Checkered", "things": ["", "Flower"], "x": 144, "y": 532, "xnum": 8, "ynum": 2, "xwidth": 4, "yheight": 4 },
                { "thing": "Sign", "x": 72, "y": 536 },
                { "macro": "Checkered", "things": ["DirtClean", "DirtWhite"], "x": 48, "y": 544, "xnum": 2, "ynum": 4 },
                { "thing": "DirtMedium", "x": 64, "y": 544, "width": 32, "height": 16 },
                { "macro": "Checkered", "things": ["", "Flower"], "x": 64, "y": 548, "xnum": 8, "ynum": 2, "xwidth": 4, "yheight": 4 },
                { "macro": "Checkered", "things": ["", "Flower"], "x": 144, "y": 548, "xnum": 8, "ynum": 2, "xwidth": 4, "yheight": 4 },
                { "macro": "Checkered", "things": ["DirtClean", "DirtWhite"], "x": 64, "y": 560, "xnum": 6, "ynum": 2 },
                { "thing": "Tree", "x": 128, "y": 560 },
                { "thing": "DirtMedium", "x": 112, "y": 568, "width": 80, "height": 24 },
                { "thing": "PlantSmall", "x": 112, "y": 568, "width": 80, "height": 24 },
                { "thing": "DirtMedium", "x": 48, "y": 576, "width": 32, "height": 16 },
                { "thing": "PlantSmall", "x": 48, "y": 576, "width": 32, "height": 16 },
                { "thing": "DirtWhite", "x": 80, "y": 576, "width": 16, "height": 16 },
                { "thing": "FenceVertical", "x": 80, "y": 576, "width": 8, "height": 16 },
                { "thing": "ThemePlayer", "x": 88, "y": 576, "width": 24, "theme": "Viridian City from Pallet Town" },
                { "macro": "Checkered", "things": ["DirtClean", "DirtWhite"], "x": 96, "y": 576, "xnum": 2, "ynum": 2 },
                { "thing": "AreaSpawner", "y": 584, "width": 608, "map": "Viridian City", "area": "Land", "direction": 1, "offsetX": -48 }
            ]
        }
    }
};